# Whether to show config errors in chat when a player uses /orestack reload
debug: true

# Generates example files and folders
generate-examples: true

# Checks for available updates on startup and every 24 hours
check-for-updates: true   # PREMIUM required to disable

# Enables bStats metrics collection (https://bstats.org/plugin/bukkit/Orestack/24502)
metrics: true   # PREMIUM required to disable

# Dumps the giant Orestack logo in console on startup and on reload
dump-logo: true   # PREMIUM required to disable

# The language file that should be used (en = en.yml)
language: en

# The auto save timer, if not set or set to 0 data will only be saved on shutdown or on /orestack reload
auto-save: 0

# Whether to keep the blocks (regrown stage) when a generator is removed
keep-blocks-on-remove: false

# The wand used to select a region
structure-wand:
  material: golden pickaxe
  name: '&6&lOrestack Wand'
  glow: true
  lore:
    - '&fleft-click to select first corner'
    - '&fright-click to select second corner'

# The generator item used to place and break generators
generator-tool:
  material: terracotta   # Replaced by the last stage block
  name: '&b&l{generator_tc} Generator ({generator_rotation_tc})'
  glow: true
  lore:
    - '&fright-click to place'
    - '&fleft-click to break'
    - '&fshift + left-click (air) to rotate'

# Blocks that should be ignored when using /orestack structure save <file-name>
structure-blacklist:
  - AIR
  - BEDROCK

############################################################
#                           Drops
############################################################
# Compatible Actions: giveItem, dropItem, dropItemAtPlayer, dropItemAtBlock

# Items affected by the Fortune enchantment from the player's tool.
# Can be overridden with the 'doFortune=true|false' flag in individual actions.
apply-fortune:
  - coal
  - diamond
  - emerald
  - lapis_lazuli
  - redstone
  - quartz
#  - raw_copper   # 1.17+
#  - dirt         # Supports any item type


############################################################
#                 Generator Health Mechanic
############################################################
# Compatible actions: damageGenerator

# The default delay between each hit, it can be overridden in the generator stage.
hit-cooldown: 4   # If the player hits faster that this, the hit will be ignored.

# The default damage dealt.
default-damage: 1

# Whether efficiency on a tool increases the damage dealt.
efficiency-damage: true   # 1 damage per efficiency level

# Whether to reduce damage if the tool is on cooldown.
reduced-cooldown-damage: true

# The damage amount for a block based on the tool type.
damage-by-tool-type:
  # ===== Wood =====
  - blocks:
      - oak_log
      - oak_wood
      - spruce_log
      - spruce_wood
      - birch_log
      - birch_wood
      - jungle_log
      - jungle_wood
      - acacia_log
      - acacia_wood
      - dark_oak_log
      - dark_oak_wood
      - crimson_stem
      - crimson_hyphae
      - warped_stem
      - warped_hyphae
      #- mangrove_log    # 1.19+
      #- mangrove_wood   # 1.19+
      #- cherry_log    # 1.20+
      #- cherry_wood   # 1.20+
      #- pale_oak_log    # 1.21+
      #- pale_oak_wood   # 1.21+
    tools:
      #air: 1 # use air to set the damage for an empty hand
      wooden_axe: 1-3
      stone_axe: 2-4
      iron_axe: 3-5
      gold_axe: 4-6
      diamond_axe: 5-7
      netherite_axe: 6-8

  # ===== Ores =====
  - blocks:
      - cobblestone
      - stone
      - coal_ore
      #- copper_ore   # 1.17+
      - iron_ore
      - gold_ore
      - diamond_ore
      - emerald_ore
    tools:
      wooden_pickaxe: 1-3
      stone_pickaxe: 2-4
      iron_axe: 3-5
      gold_axe: 4-6
      diamond_axe: 5-7
      netherite_axe: 6-8




