# Whether to show config errors in chat when a player uses /orestack reload
debug: true

# Generates example files and folders
generate-examples: true

# Checks for available updates on startup and every 24 hours
check-for-updates: true

# Enables bStats metrics collection (https://bstats.org/plugin/bukkit/Orestack/24502)
metrics: true

# Dumps the giant Orestack logo in console on startup and on reload
dump-logo: true

# The language file that should be used (en = en.yml)
language: en

# The auto save timer, if not set or set to 0 data will only be saved on shutdown or on /orestack reload
auto-save: 0

# Blocks that should be ignored when using /orestack structure save <file-name>
structure-blacklist:
  - AIR
  - BEDROCK

# Items to apply fortune enchant from the player's tool.
# Compatible Actions: giveItem, dropItem, dropItemAtPlayer, dropItemAtBlock. (Can be overridden with doFortune=true/false flag)
do-fortune-whitelist:
  - coal
  - diamond
  - emerald
  - lapis_lazuli
  - redstone
  - quartz
#  - raw_copper   # 1.17+
#  - dirt         # Supports any item type

# Whether to keep the blocks (regrown stage) when a generator is removed
keep-blocks-on-remove: false

# The wand used to select a region
structure-wand:
  material: golden pickaxe
  name: '&6&lOrestack Wand'
  glow: true
  lore:
    - '&fleft-click to select first corner'
    - '&fright-click to select second corner'

# The generator item used to place and break generators
generator-tool:
  material: terracotta   # Replaced by the last stage block
  name: '&b&l{generator_tc} Generator ({generator_rotation_tc})'
  glow: true
  lore:
    - '&fright-click to place'
    - '&fleft-click to break'
    - '&fshift + left-click (air) to rotate'


