debug: true

generate-examples: true

check-for-updates: true

#Required, the language file that should be used (en = en.yml)
language: en

# The auto save timer, if not set or set to 0 data will only be saved on shutdown or on /orestack reload
auto-save: 0

