debug: true

generate-examples: true

check-for-updates: true

# The language file that should be used (en = en.yml)
# Requires restart for command ids, parameters, permissions, and descriptions to take effect
language: en

# The auto save timer, if not set or set to 0 data will only be saved on shutdown or on /orestack reload
auto-save: 0

# Blocks that should be ignored when using /orestack structure save
structure-save-blacklist:
  - AIR
  - BEDROCK

# Tools are only intended for admin use
generator-tool:
  material: paper   # Replaced by the last stage block
  name: '&b&l%generator_tc% Generator (%generator_rotation_tc%)'
  glow: true
  lore:
    - '&fright-click to place'
    - '&fleft-click to break'
    - '&fshift + left-click (air) to rotate'

wand-tool:
  material: golden pickaxe
  name: '&6&lGenerator Wand'
  glow: true
  lore:
    - '&fleft-click to select first corner'
    - '&fright-click to select second corner'

