main: io.github.pigaut.orestack.OrestackPlugin
name: Orestack
version: 3.29.1
api-version: 1.16
author: pigaut
description: Create resources with custom gathering mechanics
softdepend:
  - Vault
  - PlaceholderAPI
  - WorldGuard
  - DecentHolograms

libraries:
  - com.h2database:h2:2.3.232
  - com.zaxxer:HikariCP:5.1.0
  - org.snakeyaml:snakeyaml-engine:2.9
  - com.github.cryptomorin:XSeries:13.2.0

