main: io.github.pigaut.orestack.OrestackPlugin
name: Orestack
version: 3.21.1
api-version: 1.16
author: pigaut
description: Create RPG gathering zones in your protected regions
softdepend:
  - Vault
  - PlaceholderAPI

libraries:
  - com.h2database:h2:2.3.232
  - com.zaxxer:HikariCP:5.1.0

