package io.github.pigaut.rpg.core.tag;

import io.github.pigaut.rpg.bukkit.material.*;
import org.bukkit.*;
import org.jetbrains.annotations.*;

import java.util.*;

public enum MaterialGroup implements MaterialTag {

    RAW_OAK(Set.of(
            "OAK_LOG", "OAK_WOOD"
    )),
    STRIPPED_OAK(Set.of(
            "STRIPPED_OAK_LOG", "STRIPPED_OAK_WOOD"
    )),
    OAK(Set.of(
            "OAK_LOG", "OAK_WOOD", "STRIPPED_OAK_LOG", "STRIPPED_OAK_WOOD",
            "OAK_PLANKS", "OAK_STAIRS", "OAK_SLAB", "OAK_FENCE", "OAK_FENCE_GATE",
            "OAK_DOOR", "OAK_TRAPDOOR", "OAK_PRESSURE_PLATE", "OAK_BUTTON",
            "OAK_SIGN", "OAK_WALL_SIGN", "OAK_HANGING_SIGN", "OAK_WALL_HANGING_SIGN"
    )),

    RAW_SPRUCE(Set.of(
            "SPRUCE_LOG", "SPRUCE_WOOD"
    )),
    STRIPPED_SPRUCE(Set.of(
            "STRIPPED_SPRUCE_LOG", "STRIPPED_SPRUCE_WOOD"
    )),
    SPRUCE(Set.of(
            "SPRUCE_LOG", "SPRUCE_WOOD", "STRIPPED_SPRUCE_LOG", "STRIPPED_SPRUCE_WOOD",
            "SPRUCE_PLANKS", "SPRUCE_STAIRS", "SPRUCE_SLAB", "SPRUCE_FENCE", "SPRUCE_FENCE_GATE",
            "SPRUCE_DOOR", "SPRUCE_TRAPDOOR", "SPRUCE_PRESSURE_PLATE", "SPRUCE_BUTTON",
            "SPRUCE_SIGN", "SPRUCE_WALL_SIGN", "SPRUCE_HANGING_SIGN", "SPRUCE_WALL_HANGING_SIGN"
    )),

    RAW_BIRCH(Set.of(
            "BIRCH_LOG", "BIRCH_WOOD"
    )),
    STRIPPED_BIRCH(Set.of(
            "STRIPPED_BIRCH_LOG", "STRIPPED_BIRCH_WOOD"
    )),
    BIRCH(Set.of(
            "BIRCH_LOG", "BIRCH_WOOD", "STRIPPED_BIRCH_LOG", "STRIPPED_BIRCH_WOOD",
            "BIRCH_PLANKS", "BIRCH_STAIRS", "BIRCH_SLAB", "BIRCH_FENCE", "BIRCH_FENCE_GATE",
            "BIRCH_DOOR", "BIRCH_TRAPDOOR", "BIRCH_PRESSURE_PLATE", "BIRCH_BUTTON",
            "BIRCH_SIGN", "BIRCH_WALL_SIGN", "BIRCH_HANGING_SIGN", "BIRCH_WALL_HANGING_SIGN"
    )),

    RAW_JUNGLE(Set.of(
            "JUNGLE_LOG", "JUNGLE_WOOD"
    )),
    STRIPPED_JUNGLE(Set.of(
            "STRIPPED_JUNGLE_LOG", "STRIPPED_JUNGLE_WOOD"
    )),
    JUNGLE(Set.of(
            "JUNGLE_LOG", "JUNGLE_WOOD", "STRIPPED_JUNGLE_LOG", "STRIPPED_JUNGLE_WOOD",
            "JUNGLE_PLANKS", "JUNGLE_STAIRS", "JUNGLE_SLAB", "JUNGLE_FENCE", "JUNGLE_FENCE_GATE",
            "JUNGLE_DOOR", "JUNGLE_TRAPDOOR", "JUNGLE_PRESSURE_PLATE", "JUNGLE_BUTTON",
            "JUNGLE_SIGN", "JUNGLE_WALL_SIGN", "JUNGLE_HANGING_SIGN", "JUNGLE_WALL_HANGING_SIGN"
    )),

    RAW_ACACIA(Set.of(
            "ACACIA_LOG", "ACACIA_WOOD"
    )),
    STRIPPED_ACACIA(Set.of(
            "STRIPPED_ACACIA_LOG", "STRIPPED_ACACIA_WOOD"
    )),
    ACACIA(Set.of(
            "ACACIA_LOG", "ACACIA_WOOD", "STRIPPED_ACACIA_LOG", "STRIPPED_ACACIA_WOOD",
            "ACACIA_PLANKS", "ACACIA_STAIRS", "ACACIA_SLAB", "ACACIA_FENCE", "ACACIA_FENCE_GATE",
            "ACACIA_DOOR", "ACACIA_TRAPDOOR", "ACACIA_PRESSURE_PLATE", "ACACIA_BUTTON",
            "ACACIA_SIGN", "ACACIA_WALL_SIGN", "ACACIA_HANGING_SIGN", "ACACIA_WALL_HANGING_SIGN"
    )),

    RAW_DARK_OAK(Set.of(
            "DARK_OAK_LOG", "DARK_OAK_WOOD"
    )),
    STRIPPED_DARK_OAK(Set.of(
            "STRIPPED_DARK_OAK_LOG", "STRIPPED_DARK_OAK_WOOD"
    )),
    DARK_OAK(Set.of(
            "DARK_OAK_LOG", "DARK_OAK_WOOD", "STRIPPED_DARK_OAK_LOG", "STRIPPED_DARK_OAK_WOOD",
            "DARK_OAK_PLANKS", "DARK_OAK_STAIRS", "DARK_OAK_SLAB", "DARK_OAK_FENCE", "DARK_OAK_FENCE_GATE",
            "DARK_OAK_DOOR", "DARK_OAK_TRAPDOOR", "DARK_OAK_PRESSURE_PLATE", "DARK_OAK_BUTTON",
            "DARK_OAK_SIGN", "DARK_OAK_WALL_SIGN", "DARK_OAK_HANGING_SIGN", "DARK_OAK_WALL_HANGING_SIGN"
    )),

    RAW_MANGROVE(Set.of(
            "MANGROVE_LOG", "MANGROVE_WOOD"
    )),
    STRIPPED_MANGROVE(Set.of(
            "STRIPPED_MANGROVE_LOG", "STRIPPED_MANGROVE_WOOD"
    )),
    MANGROVE(Set.of(
            "MANGROVE_LOG", "MANGROVE_WOOD", "STRIPPED_MANGROVE_LOG", "STRIPPED_MANGROVE_WOOD",
            "MANGROVE_PLANKS", "MANGROVE_STAIRS", "MANGROVE_SLAB", "MANGROVE_FENCE", "MANGROVE_FENCE_GATE",
            "MANGROVE_DOOR", "MANGROVE_TRAPDOOR", "MANGROVE_PRESSURE_PLATE", "MANGROVE_BUTTON",
            "MANGROVE_SIGN", "MANGROVE_WALL_SIGN", "MANGROVE_HANGING_SIGN", "MANGROVE_WALL_HANGING_SIGN",
            "MANGROVE_PROPAGULE", "MANGROVE_LEAVES", "MANGROVE_ROOTS", "MUDDY_MANGROVE_ROOTS"
    )),

    RAW_CHERRY(Set.of(
            "CHERRY_LOG", "CHERRY_WOOD"
    )),
    STRIPPED_CHERRY(Set.of(
            "STRIPPED_CHERRY_LOG", "STRIPPED_CHERRY_WOOD"
    )),
    CHERRY(Set.of(
            "CHERRY_LOG", "CHERRY_WOOD", "STRIPPED_CHERRY_LOG", "STRIPPED_CHERRY_WOOD",
            "CHERRY_PLANKS", "CHERRY_STAIRS", "CHERRY_SLAB", "CHERRY_FENCE", "CHERRY_FENCE_GATE",
            "CHERRY_DOOR", "CHERRY_TRAPDOOR", "CHERRY_PRESSURE_PLATE", "CHERRY_BUTTON",
            "CHERRY_SIGN", "CHERRY_WALL_SIGN", "CHERRY_HANGING_SIGN", "CHERRY_WALL_HANGING_SIGN"
    )),

    RAW_PALE_OAK(Set.of(
            "PALE_OAK_LOG", "PALE_OAK_WOOD"
    )),
    STRIPPED_PALE_OAK(Set.of(
            "STRIPPED_PALE_OAK_LOG", "STRIPPED_PALE_OAK_WOOD"
    )),
    PALE_OAK(Set.of(
            "PALE_OAK_LOG", "PALE_OAK_WOOD", "STRIPPED_PALE_OAK_LOG", "STRIPPED_PALE_OAK_WOOD",
            "PALE_OAK_PLANKS", "PALE_OAK_STAIRS", "PALE_OAK_SLAB", "PALE_OAK_FENCE", "PALE_OAK_FENCE_GATE",
            "PALE_OAK_DOOR", "PALE_OAK_TRAPDOOR", "PALE_OAK_PRESSURE_PLATE", "PALE_OAK_BUTTON",
            "PALE_OAK_SIGN", "PALE_OAK_WALL_SIGN", "PALE_OAK_HANGING_SIGN", "PALE_OAK_WALL_HANGING_SIGN"
    )),

    RAW_CRIMSON(Set.of(
            "CRIMSON_STEM", "CRIMSON_HYPHAE"
    )),
    STRIPPED_CRIMSON(Set.of(
            "STRIPPED_CRIMSON_STEM", "STRIPPED_CRIMSON_HYPHAE"
    )),
    CRIMSON(Set.of(
            "CRIMSON_STEM", "CRIMSON_HYPHAE", "STRIPPED_CRIMSON_STEM", "STRIPPED_CRIMSON_HYPHAE",
            "CRIMSON_PLANKS", "CRIMSON_STAIRS", "CRIMSON_SLAB", "CRIMSON_FENCE", "CRIMSON_FENCE_GATE",
            "CRIMSON_DOOR", "CRIMSON_TRAPDOOR", "CRIMSON_PRESSURE_PLATE", "CRIMSON_BUTTON",
            "CRIMSON_SIGN", "CRIMSON_WALL_SIGN", "CRIMSON_HANGING_SIGN", "CRIMSON_WALL_HANGING_SIGN",
            "CRIMSON_FUNGUS", "CRIMSON_ROOTS"
    )),

    RAW_WARPED(Set.of(
            "WARPED_STEM", "WARPED_HYPHAE"
    )),
    STRIPPED_WARPED(Set.of(
            "STRIPPED_WARPED_STEM", "STRIPPED_WARPED_HYPHAE"
    )),
    WARPED(Set.of(
            "WARPED_STEM", "WARPED_HYPHAE", "STRIPPED_WARPED_STEM", "STRIPPED_WARPED_HYPHAE",
            "WARPED_PLANKS", "WARPED_STAIRS", "WARPED_SLAB", "WARPED_FENCE", "WARPED_FENCE_GATE",
            "WARPED_DOOR", "WARPED_TRAPDOOR", "WARPED_PRESSURE_PLATE", "WARPED_BUTTON",
            "WARPED_SIGN", "WARPED_WALL_SIGN", "WARPED_HANGING_SIGN", "WARPED_WALL_HANGING_SIGN",
            "WARPED_FUNGUS", "WARPED_ROOTS"
    )),

    RAW_BAMBOO(Set.of(
            "BAMBOO_BLOCK"
    )),
    STRIPPED_BAMBOO(Set.of(
            "STRIPPED_BAMBOO_BLOCK"
    )),
    BAMBOO(Set.of(
            "BAMBOO_BLOCK", "STRIPPED_BAMBOO_BLOCK", "BAMBOO_PLANKS", "BAMBOO_MOSAIC",
            "BAMBOO_STAIRS", "BAMBOO_MOSAIC_STAIRS", "BAMBOO_SLAB", "BAMBOO_MOSAIC_SLAB",
            "BAMBOO_FENCE", "BAMBOO_FENCE_GATE", "BAMBOO_DOOR", "BAMBOO_TRAPDOOR",
            "BAMBOO_PRESSURE_PLATE", "BAMBOO_BUTTON", "BAMBOO_SIGN", "BAMBOO_WALL_SIGN",
            "BAMBOO_HANGING_SIGN", "BAMBOO_WALL_HANGING_SIGN"
    ));

    private final Set<Material> materials = new HashSet<>();

    MaterialGroup(Set<String> materialNames) {
        for (String materialName : materialNames) {
            Material material = MaterialUtil.getMaterial(materialName);
            if (material != null) {
                materials.add(material);
            }
        }
    }

    public @NotNull Set<Material> getMaterials() {
        return new HashSet<>(materials);
    }

    public boolean contains(@NotNull Material material) {
        return materials.contains(material);
    }

}
