package io.github.pigaut.rpg.bukkit;

import org.bukkit.*;
import org.jetbrains.annotations.*;

import java.util.*;

public class SoundUtil {

    private static final Map<String, Sound> SOUNDS = new HashMap<>();

    public static @Nullable Sound getSound(@NotNull String name) {
        return SOUNDS.get(name.toLowerCase(Locale.ENGLISH));
    }

    private static void registerSound(String... names) {
        for (String name : names) {
            Sound foundSound = Registry.SOUNDS.get(NamespacedKey.minecraft(name));
            if (foundSound != null) {
                for (String id : names) {
                    SOUNDS.put(id, foundSound);
                }
            }
        }
    }

    static {
        registerSound("ambient.underwater.loop", "ambient_underwater_exit");
        registerSound("ambient.underwater.loop.additions", "ambient_underwater_exit");
        registerSound("ambient.underwater.loop.additions.rare", "ambient_underwater_exit");
        registerSound("ambient.underwater.loop.additions.ultra_rare", "ambient_underwater_exit");
        registerSound("block.anvil.break", "anvil_break");
        registerSound("block.anvil.hit", "block_anvil_fall");
        registerSound("block.anvil.land", "anvil_land");
        registerSound("block.anvil.place", "block_anvil_fall");
        registerSound("block.anvil.step", "block_anvil_fall");
        registerSound("block.anvil.use", "anvil_use");
        registerSound("block.beacon.deactivate", "block_beacon_ambient");
        registerSound("block.beacon.power_select", "block_beacon_ambient");
        registerSound("block.chest.close", "chest_close", "entity_chest_close");
        registerSound("block.chest.open", "chest_open", "entity_chest_open");
        registerSound("block.fire.ambient", "fire");
        registerSound("block.fire.extinguish", "fizz");
        registerSound("block.glass.break", "glass");
        registerSound("block.grass.break", "dig_grass");
        registerSound("block.grass.step", "step_grass");
        registerSound("block.gravel.break", "dig_gravel");
        registerSound("block.gravel.step", "step_gravel");
        registerSound("block.ladder.step", "step_ladder");
        registerSound("block.lava.ambient", "lava");
        registerSound("block.lava.pop", "lava_pop");
        registerSound("block.lily_pad.place", "block_waterlily_place");
        registerSound("block.metal_pressure_plate.click_off", "block_metal_pressureplate_click_off");
        registerSound("block.metal_pressure_plate.click_on", "block_metal_pressureplate_click_on");
        registerSound("block.note_block.basedrum", "note_bass_drum", "block_note_basedrum");
        registerSound("block.note_block.bass", "note_bass", "block_note_bass");
        registerSound("block.note_block.bell", "block_note_bell");
        registerSound("block.note_block.chime", "block_note_chime");
        registerSound("block.note_block.flute", "block_note_flute");
        registerSound("block.note_block.guitar", "note_bass_guitar", "block_note_guitar");
        registerSound("block.note_block.harp", "note_piano", "block_note_harp");
        registerSound("block.note_block.hat", "note_sticks", "block_note_hat");
        registerSound("block.note_block.pling", "note_pling", "block_note_pling");
        registerSound("block.note_block.snare", "note_snare_drum", "block_note_snare");
        registerSound("block.note_block.xylophone", "block_note_xylophone");
        registerSound("block.piston.contract", "piston_retract");
        registerSound("block.piston.extend", "piston_extend");
        registerSound("block.portal.ambient", "portal");
        registerSound("block.portal.travel", "portal_travel");
        registerSound("block.portal.trigger", "portal_trigger");
        registerSound("block.sand.break", "dig_sand");
        registerSound("block.sand.step", "step_sand");
        registerSound("block.slime_block.break", "block_slime_break");
        registerSound("block.slime_block.fall", "block_slime_fall");
        registerSound("block.slime_block.hit", "block_slime_hit");
        registerSound("block.slime_block.place", "block_slime_place");
        registerSound("block.slime_block.step", "block_slime_step");
        registerSound("block.snow.break", "dig_snow");
        registerSound("block.snow.step", "step_snow");
        registerSound("block.stone.break", "dig_stone");
        registerSound("block.stone_pressure_plate.click_off", "block_stone_pressureplate_click_off");
        registerSound("block.stone_pressure_plate.click_on", "block_stone_pressureplate_click_on");
        registerSound("block.stone.step", "step_stone");
        registerSound("block.sweet_berry_bush.pick_berries", "item.sweet_berries.pick_from_bush");
        registerSound("block.water.ambient", "water");
        registerSound("block.wet_grass.place", "block_wet_grass_hit");
        registerSound("block.wet_grass.step", "block_wet_grass_hit");
        registerSound("block.wooden_button.click_off", "wood_click", "block_wood_button_click_off");
        registerSound("block.wooden_button.click_on", "wood_click", "block_wood_button_click_on");
        registerSound("block.wooden_door.close", "door_close");
        registerSound("block.wooden_door.open", "door_open");
        registerSound("block.wooden_pressure_plate.click_off", "block_wood_pressureplate_click_off");
        registerSound("block.wooden_pressure_plate.click_on", "block_wood_pressureplate_click_on");
        registerSound("block.wood.break", "dig_wood");
        registerSound("block.wood.step", "step_wood");
        registerSound("block.wool.break", "dig_wool", "block_cloth_break");
        registerSound("block.wool.hit", "block_cloth_hit");
        registerSound("block.wool.place", "block_wool_fall", "block_cloth_place");
        registerSound("block.wool.step", "step_wool", "block_cloth_step");
        registerSound("entity.armor_stand.break", "entity_armorstand_break");
        registerSound("entity.armor_stand.fall", "entity_armorstand_fall");
        registerSound("entity.armor_stand.hit", "entity_armorstand_hit");
        registerSound("entity.armor_stand.place", "entity_armorstand_place");
        registerSound("entity.arrow.hit", "arrow_hit");
        registerSound("entity.arrow.hit_player", "successful_hit");
        registerSound("entity.arrow.shoot", "shoot_arrow");
        registerSound("entity.bat.ambient", "bat_idle");
        registerSound("entity.bat.death", "bat_death");
        registerSound("entity.bat.hurt", "bat_hurt");
        registerSound("entity.bat.loop", "bat_loop");
        registerSound("entity.bat.takeoff", "bat_takeoff");
        registerSound("entity.blaze.ambient", "blaze_breath");
        registerSound("entity.blaze.death", "blaze_death");
        registerSound("entity.blaze.hurt", "blaze_hit");
        registerSound("entity.cat.ambient", "cat_meow");
        registerSound("entity.cat.eat");
        registerSound("entity.cat.hiss", "cat_hiss");
        registerSound("entity.cat.hurt", "cat_hit");
        registerSound("entity.cat.purr", "cat_purr");
        registerSound("entity.cat.purreow", "cat_purreow");
        registerSound("entity.chicken.ambient", "chicken_idle");
        registerSound("entity.chicken.egg", "chicken_egg_pop");
        registerSound("entity.chicken.hurt", "chicken_hurt");
        registerSound("entity.chicken.step", "chicken_walk");
        registerSound("entity.cow.ambient", "cow_idle");
        registerSound("entity.cow.hurt", "cow_hurt");
        registerSound("entity.cow.step", "cow_walk");
        registerSound("entity.creeper.death", "creeper_death");
        registerSound("entity.creeper.primed", "creeper_hiss");
        registerSound("entity.donkey.ambient", "donkey_idle");
        registerSound("entity.donkey.angry", "donkey_angry");
        registerSound("entity.donkey.death", "donkey_death");
        registerSound("entity.donkey.hurt", "donkey_hit");
        registerSound("entity.dragon_fireball.explode", "entity_enderdragon_fireball_explode");
        registerSound("entity.enderman.ambient", "enderman_idle", "entity_endermen_ambient");
        registerSound("entity.enderman.death", "enderman_death", "entity_endermen_death");
        registerSound("entity.enderman.hurt", "enderman_hit", "entity_endermen_hurt");
        registerSound("entity.enderman.scream", "enderman_scream", "entity_endermen_scream");
        registerSound("entity.enderman.stare", "enderman_stare", "entity_endermen_stare");
        registerSound("entity.enderman.teleport", "enderman_teleport", "entity_endermen_teleport");
        registerSound("entity.ender_dragon.ambient", "enderdragon_wings", "entity_enderdragon_ambient");
        registerSound("entity.ender_dragon.death", "enderdragon_death", "entity_enderdragon_death");
        registerSound("entity.ender_dragon.flap", "enderdragon_wings", "entity_enderdragon_flap");
        registerSound("entity.ender_dragon.growl", "enderdragon_growl", "entity_enderdragon_growl");
        registerSound("entity.ender_dragon.hurt", "enderdragon_hit", "entity_enderdragon_hurt");
        registerSound("entity.ender_dragon.shoot", "entity_enderdragon_shoot");
        registerSound("entity.ender_eye.launch", "entity_endereye_launch");
        registerSound("entity.ender_pearl.throw", "entity_enderpearl_throw");
        registerSound("entity.evoker.ambient", "entity_evocation_illager_ambient");
        registerSound("entity.evoker.cast_spell", "entity_evocation_illager_cast_spell");
        registerSound("entity.evoker.death", "entity_evocation_illager_death");
        registerSound("entity.evoker_fangs.attack", "entity_evocation_fangs_attack");
        registerSound("entity.evoker.hurt", "entity_evocation_illager_hurt");
        registerSound("entity.evoker.prepare_attack", "entity_evocation_illager_prepare_attack");
        registerSound("entity.evoker.prepare_summon", "entity_evocation_illager_prepare_summon");
        registerSound("entity.evoker.prepare_wololo", "entity_evocation_illager_prepare_wololo");
        registerSound("entity.firework_rocket.blast", "firework_blast", "entity_firework_blast");
        registerSound("entity.firework_rocket.blast_far", "firework_blast2", "entity_firework_blast_far");
        registerSound("entity.firework_rocket.large_blast", "firework_large_blast", "entity_firework_large_blast");
        registerSound("entity.firework_rocket.large_blast_far", "firework_large_blast2", "entity_firework_large_blast_far");
        registerSound("entity.firework_rocket.launch", "firework_launch", "entity_firework_launch");
        registerSound("entity.firework_rocket.twinkle", "firework_twinkle", "entity_firework_twinkle");
        registerSound("entity.firework_rocket.twinkle_far", "firework_twinkle2", "entity_firework_twinkle_far");
        registerSound("entity.fishing_bobber.splash", "splash2", "entity_bobber_splash");
        registerSound("entity.fishing_bobber.throw", "entity_bobber_throw");
        registerSound("entity.generic.big_fall", "fall_big");
        registerSound("entity.generic.drink", "drink");
        registerSound("entity.generic.eat", "eat");
        registerSound("entity.generic.explode", "explode");
        registerSound("entity.generic.small_fall", "fall_small");
        registerSound("entity.generic.splash", "splash");
        registerSound("entity.generic.swim", "swim");
        registerSound("entity.ghast.ambient", "ghast_moan");
        registerSound("entity.ghast.death", "ghast_death");
        registerSound("entity.ghast.hurt", "ghast_scream2");
        registerSound("entity.ghast.scream", "ghast_scream");
        registerSound("entity.ghast.shoot", "ghast_fireball");
        registerSound("entity.ghast.warn", "ghast_charge");
        registerSound("entity.horse.ambient", "horse_idle");
        registerSound("entity.horse.angry", "horse_angry");
        registerSound("entity.horse.armor", "horse_armor");
        registerSound("entity.horse.breathe", "horse_breath");
        registerSound("entity.horse.death", "horse_death");
        registerSound("entity.horse.eat");
        registerSound("entity.horse.gallop", "horse_gallop");
        registerSound("entity.horse.hurt", "horse_hit");
        registerSound("entity.horse.jump", "horse_jump");
        registerSound("entity.horse.land", "horse_land");
        registerSound("entity.horse.saddle", "horse_saddle");
        registerSound("entity.horse.step", "horse_soft");
        registerSound("entity.horse.step_wood", "horse_wood");
        registerSound("entity.hostile.big_fall", "fall_big");
        registerSound("entity.hostile.small_fall", "fall_small");
        registerSound("entity.hostile.splash", "splash");
        registerSound("entity.hostile.swim", "swim");
        registerSound("entity.illusioner.ambient", "entity_illusion_illager_ambient");
        registerSound("entity.illusioner.cast_spell", "entity_illusion_illager_cast_spell");
        registerSound("entity.illusioner.death", "entity_illusioner_cast_death", "entity_illusion_illager_death");
        registerSound("entity.illusioner.hurt", "entity_illusion_illager_hurt");
        registerSound("entity.illusioner.mirror_move", "entity_illusion_illager_mirror_move");
        registerSound("entity.illusioner.prepare_blindness", "entity_illusion_illager_prepare_blindness");
        registerSound("entity.illusioner.prepare_mirror", "entity_illusion_illager_prepare_mirror");
        registerSound("entity.iron_golem.attack", "irongolem_throw", "entity_irongolem_attack");
        registerSound("entity.iron_golem.death", "irongolem_death", "entity_irongolem_death");
        registerSound("entity.iron_golem.hurt", "irongolem_hit", "entity_irongolem_hurt");
        registerSound("entity.iron_golem.step", "irongolem_walk", "entity_irongolem_step");
        registerSound("entity.item.break", "item_break");
        registerSound("entity.item_frame.add_item", "entity_itemframe_add_item");
        registerSound("entity.item_frame.break", "entity_itemframe_break");
        registerSound("entity.item_frame.place", "entity_itemframe_place");
        registerSound("entity.item_frame.remove_item", "entity_itemframe_remove_item");
        registerSound("entity.item_frame.rotate_item", "entity_itemframe_rotate_item");
        registerSound("entity.item.pickup", "item_pickup");
        registerSound("entity.leash_knot.break", "entity_leashknot_break");
        registerSound("entity.leash_knot.place", "entity_leashknot_place");
        registerSound("entity.lightning_bolt.impact", "entity_lightning_impact", "ambience_thunder");
        registerSound("entity.lightning_bolt.thunder", "entity_lightning_thunder", "ambience_thunder");
        registerSound("entity.lingering_potion.throw", "entity_lingeringpotion_throw");
        registerSound("entity.magma_cube.death", "entity_magmacube_death");
        registerSound("entity.magma_cube.death_small", "entity_small_magmacube_death");
        registerSound("entity.magma_cube.hurt", "entity_magmacube_hurt");
        registerSound("entity.magma_cube.hurt_small", "entity_small_magmacube_hurt");
        registerSound("entity.magma_cube.jump", "magmacube_jump", "entity_magmacube_jump");
        registerSound("entity.magma_cube.squish", "magmacube_walk", "entity_magmacube_squish");
        registerSound("entity.magma_cube.squish_small", "magmacube_walk2", "entity_small_magmacube_squish");
        registerSound("entity.minecart.inside", "minecart_inside");
        registerSound("entity.minecart.riding", "minecart_base");
        registerSound("entity.mule.chest", "entity_mule_ambient");
        registerSound("entity.mule.death", "entity_mule_ambient");
        registerSound("entity.mule.hurt", "entity_mule_ambient");
        registerSound("entity.pig.ambient", "pig_idle");
        registerSound("entity.pig.death", "pig_death");
        registerSound("entity.pig.saddle", "entity_pig_hurt");
        registerSound("entity.pig.step", "pig_walk");
        registerSound("entity.player.attack.strong", "successful_hit");
        registerSound("entity.player.big_fall", "fall_big");
        registerSound("entity.player.burp", "burp");
        registerSound("entity.player.hurt", "hurt_flesh");
        registerSound("entity.player.levelup", "level_up");
        registerSound("entity.player.small_fall", "fall_small");
        registerSound("entity.player.splash", "slash");
        registerSound("entity.player.splash.high_speed", "splash");
        registerSound("entity.player.swim", "swim");
        registerSound("entity.polar_bear.ambient_baby", "entity_polar_bear_baby_ambient");
        registerSound("entity.salmon.hurt", "entity_salmon_flop");
        registerSound("entity.sheep.ambient", "sheep_idle");
        registerSound("entity.sheep.shear", "sheep_shear");
        registerSound("entity.sheep.step", "sheep_walk");
        registerSound("entity.silverfish.ambient", "silverfish_idle");
        registerSound("entity.silverfish.death", "silverfish_kill");
        registerSound("entity.silverfish.hurt", "silverfish_hit");
        registerSound("entity.silverfish.step", "silverfish_walk");
        registerSound("entity.skeleton.ambient", "skeleton_idle");
        registerSound("entity.skeleton.death", "skeleton_death");
        registerSound("entity.skeleton_horse.ambient", "horse_skeleton_idle");
        registerSound("entity.skeleton_horse.death", "horse_skeleton_death");
        registerSound("entity.skeleton_horse.hurt", "horse_skeleton_hit");
        registerSound("entity.skeleton.hurt", "skeleton_hurt");
        registerSound("entity.skeleton.step", "skeleton_walk");
        registerSound("entity.slime.attack", "slime_attack");
        registerSound("entity.slime.hurt_small", "entity_small_slime_hurt");
        registerSound("entity.slime.jump", "slime_walk");
        registerSound("entity.slime.jump_small", "slime_walk2", "entity_small_slime_jump");
        registerSound("entity.slime.squish", "slime_walk2");
        registerSound("entity.slime.squish_small", "entity_small_slime_squish");
        registerSound("entity.snow_golem.ambient", "entity_snowman_ambient");
        registerSound("entity.snow_golem.death", "entity_snowman_death");
        registerSound("entity.snow_golem.hurt", "entity_snowman_hurt");
        registerSound("entity.snow_golem.shear");
        registerSound("entity.snow_golem.shoot", "entity_snowman_shoot");
        registerSound("entity.spider.ambient", "spider_idle");
        registerSound("entity.spider.death", "spider_death");
        registerSound("entity.spider.step", "spider_walk");
        registerSound("entity.tnt.primed", "fuse");
        registerSound("entity.tropical_fish.flop", "entity_tropical_fish_death");
        registerSound("entity.villager.ambient", "villager_idle");
        registerSound("entity.villager.death", "villager_death");
        registerSound("entity.villager.hurt", "villager_hit");
        registerSound("entity.villager.no", "villager_no");
        registerSound("entity.villager.trade", "villager_haggle", "entity_villager_trading");
        registerSound("entity.villager.yes", "villager_yes");
        registerSound("entity.vindicator.ambient", "entity_vindication_illager_ambient");
        registerSound("entity.vindicator.death", "entity_vindication_illager_death");
        registerSound("entity.vindicator.hurt", "entity_vindication_illager_hurt");
        registerSound("entity.wither.ambient", "wither_idle");
        registerSound("entity.wither.death", "wither_death");
        registerSound("entity.wither.hurt", "wither_hurt");
        registerSound("entity.wither.shoot", "wither_shoot");
        registerSound("entity.wither.spawn", "wither_spawn");
        registerSound("entity.wolf.ambient", "wolf_bark");
        registerSound("entity.wolf.death", "wolf_death");
        registerSound("entity.wolf.growl", "wolf_growl");
        registerSound("entity.wolf.howl", "wolf_howl");
        registerSound("entity.wolf.hurt", "wolf_hurt");
        registerSound("entity.wolf.pant", "wolf_pant");
        registerSound("entity.wolf.shake", "wolf_shake");
        registerSound("entity.wolf.step", "wolf_walk");
        registerSound("entity.wolf.whine", "wolf_whine");
        registerSound("entity.zombie.ambient", "zombie_idle");
        registerSound("entity.zombie.attack_iron_door", "zombie_metal");
        registerSound("entity.zombie.attack_wooden_door", "zombie_wood", "entity_zombie_attack_door_wood");
        registerSound("entity.zombie.break_wooden_door", "zombie_woodbreak", "entity_zombie_break_door_wood");
        registerSound("entity.zombie.death", "zombie_death");
        registerSound("entity.zombie_horse.ambient", "horse_zombie_idle");
        registerSound("entity.zombie_horse.death", "horse_zombie_death");
        registerSound("entity.zombie_horse.hurt", "horse_zombie_hit");
        registerSound("entity.zombie.hurt", "zombie_hurt");
        registerSound("entity.zombie.infect", "zombie_infect");
        registerSound("entity.zombie.step", "zombie_walk");
        registerSound("entity.zombie_villager.converted", "zombie_unfect");
        registerSound("entity.zombie_villager.cure", "zombie_remedy");
        registerSound("entity.zombified_piglin.ambient", "zombie_pig_idle", "entity_zombie_pig_ambient", "entity_zombie_pigman_ambient");
        registerSound("entity.zombified_piglin.angry", "zombie_pig_angry", "entity_zombie_pig_angry", "entity_zombie_pigman_angry");
        registerSound("entity.zombified_piglin.death", "zombie_pig_death", "entity_zombie_pig_death", "entity_zombie_pigman_death");
        registerSound("entity.zombified_piglin.hurt", "zombie_pig_hurt", "entity_zombie_pig_hurt", "entity_zombie_pigman_hurt");
        registerSound("item.flintandsteel.use", "fire_ignite");
        registerSound("item.trident.riptide_2", "item_trident_riptide_1");
        registerSound("item.trident.riptide_3", "item_trident_riptide_1");
        registerSound("music_disc.11", "record_11");
        registerSound("music_disc.13", "record_13");
        registerSound("music_disc.blocks", "record_blocks");
        registerSound("music_disc.cat", "record_cat");
        registerSound("music_disc.chirp", "record_chirp");
        registerSound("music_disc.far", "record_far");
        registerSound("music_disc.mall", "record_mall");
        registerSound("music_disc.mellohi", "record_mellohi");
        registerSound("music_disc.stal", "record_stal");
        registerSound("music_disc.strad", "record_strad");
        registerSound("music_disc.wait", "record_wait");
        registerSound("music_disc.ward", "record_ward");
        registerSound("music.nether.basalt_deltas", "music_nether");
        registerSound("ui.button.click", "click");
        registerSound("weather.rain", "ambience_rain");
        registerSound("ambient.cave", "ambience_cave");
        registerSound("entity.experience_orb.pickup", "orb_pickup", "entity_experience_orb_pickup", "entity_experience_orb_touch");
        registerSound("ambient.basalt_deltas.additions");
        registerSound("ambient.basalt_deltas.loop");
        registerSound("ambient.basalt_deltas.mood");
        registerSound("ambient.crimson_forest.additions");
        registerSound("ambient.crimson_forest.loop");
        registerSound("ambient.crimson_forest.mood");
        registerSound("ambient.nether_wastes.additions");
        registerSound("ambient.nether_wastes.loop");
        registerSound("ambient.nether_wastes.mood");
        registerSound("ambient.soul_sand_valley.additions");
        registerSound("ambient.soul_sand_valley.loop");
        registerSound("ambient.soul_sand_valley.mood");
        registerSound("ambient.underwater.enter");
        registerSound("ambient.underwater.exit");
        registerSound("ambient.warped_forest.additions");
        registerSound("ambient.warped_forest.loop");
        registerSound("ambient.warped_forest.mood");
        registerSound("block.amethyst_block.break");
        registerSound("block.amethyst_block.chime");
        registerSound("block.amethyst_block.fall");
        registerSound("block.amethyst_block.hit");
        registerSound("block.amethyst_block.place");
        registerSound("block.amethyst_block.resonate");
        registerSound("block.amethyst_block.step");
        registerSound("block.amethyst_cluster.break");
        registerSound("block.amethyst_cluster.fall");
        registerSound("block.amethyst_cluster.hit");
        registerSound("block.amethyst_cluster.place");
        registerSound("block.amethyst_cluster.step");
        registerSound("block.ancient_debris.break");
        registerSound("block.ancient_debris.fall");
        registerSound("block.ancient_debris.hit");
        registerSound("block.ancient_debris.place");
        registerSound("block.ancient_debris.step");
        registerSound("block.anvil.destroy");
        registerSound("block.anvil.fall");
        registerSound("block.azalea.break");
        registerSound("block.azalea.fall");
        registerSound("block.azalea.hit");
        registerSound("block.azalea_leaves.break");
        registerSound("block.azalea_leaves.fall");
        registerSound("block.azalea_leaves.hit");
        registerSound("block.azalea_leaves.place");
        registerSound("block.azalea_leaves.step");
        registerSound("block.azalea.place");
        registerSound("block.azalea.step");
        registerSound("block.bamboo.break");
        registerSound("block.bamboo.fall");
        registerSound("block.bamboo.hit");
        registerSound("block.bamboo.place");
        registerSound("block.bamboo_sapling.break");
        registerSound("block.bamboo_sapling.hit");
        registerSound("block.bamboo_sapling.place");
        registerSound("block.bamboo.step");
        registerSound("block.bamboo_wood.break");
        registerSound("block.bamboo_wood_button.click_off");
        registerSound("block.bamboo_wood_button.click_on");
        registerSound("block.bamboo_wood_door.close");
        registerSound("block.bamboo_wood_door.open");
        registerSound("block.bamboo_wood.fall");
        registerSound("block.bamboo_wood_fence_gate.close");
        registerSound("block.bamboo_wood_fence_gate.open");
        registerSound("block.bamboo_wood_hanging_sign.break");
        registerSound("block.bamboo_wood_hanging_sign.fall");
        registerSound("block.bamboo_wood_hanging_sign.hit");
        registerSound("block.bamboo_wood_hanging_sign.place");
        registerSound("block.bamboo_wood_hanging_sign.step");
        registerSound("block.bamboo_wood.hit");
        registerSound("block.bamboo_wood.place");
        registerSound("block.bamboo_wood_pressure_plate.click_off");
        registerSound("block.bamboo_wood_pressure_plate.click_on");
        registerSound("block.bamboo_wood.step");
        registerSound("block.bamboo_wood_trapdoor.close");
        registerSound("block.bamboo_wood_trapdoor.open");
        registerSound("block.barrel.close");
        registerSound("block.barrel.open");
        registerSound("block.basalt.break");
        registerSound("block.basalt.fall");
        registerSound("block.basalt.hit");
        registerSound("block.basalt.place");
        registerSound("block.basalt.step");
        registerSound("block.beacon.activate");
        registerSound("block.beacon.ambient");
        registerSound("block.beehive.drip");
        registerSound("block.beehive.enter");
        registerSound("block.beehive.exit");
        registerSound("block.beehive.shear");
        registerSound("block.beehive.work");
        registerSound("block.bell.resonate");
        registerSound("block.bell.use");
        registerSound("block.big_dripleaf.break");
        registerSound("block.big_dripleaf.fall");
        registerSound("block.big_dripleaf.hit");
        registerSound("block.big_dripleaf.place");
        registerSound("block.big_dripleaf.step");
        registerSound("block.big_dripleaf.tilt_down");
        registerSound("block.big_dripleaf.tilt_up");
        registerSound("block.blastfurnace.fire_crackle");
        registerSound("block.bone_block.break");
        registerSound("block.bone_block.fall");
        registerSound("block.bone_block.hit");
        registerSound("block.bone_block.place");
        registerSound("block.bone_block.step");
        registerSound("block.brewing_stand.brew");
        registerSound("block.bubble_column.bubble_pop");
        registerSound("block.bubble_column.upwards_ambient");
        registerSound("block.bubble_column.upwards_inside");
        registerSound("block.bubble_column.whirlpool_ambient");
        registerSound("block.bubble_column.whirlpool_inside");
        registerSound("block.cake.add_candle");
        registerSound("block.calcite.break");
        registerSound("block.calcite.fall");
        registerSound("block.calcite.hit");
        registerSound("block.calcite.place");
        registerSound("block.calcite.step");
        registerSound("block.campfire.crackle");
        registerSound("block.candle.ambient");
        registerSound("block.candle.break");
        registerSound("block.candle.extinguish");
        registerSound("block.candle.fall");
        registerSound("block.candle.hit");
        registerSound("block.candle.place");
        registerSound("block.candle.step");
        registerSound("block.cave_vines.break");
        registerSound("block.cave_vines.fall");
        registerSound("block.cave_vines.hit");
        registerSound("block.cave_vines.pick_berries");
        registerSound("block.cave_vines.place");
        registerSound("block.cave_vines.step");
        registerSound("block.chain.break");
        registerSound("block.chain.fall");
        registerSound("block.chain.hit");
        registerSound("block.chain.place");
        registerSound("block.chain.step");
        registerSound("block.cherry_leaves.break");
        registerSound("block.cherry_leaves.fall");
        registerSound("block.cherry_leaves.hit");
        registerSound("block.cherry_leaves.place");
        registerSound("block.cherry_leaves.step");
        registerSound("block.cherry_sapling.break");
        registerSound("block.cherry_sapling.fall");
        registerSound("block.cherry_sapling.hit");
        registerSound("block.cherry_sapling.place");
        registerSound("block.cherry_sapling.step");
        registerSound("block.cherry_wood.break");
        registerSound("block.cherry_wood_button.click_off");
        registerSound("block.cherry_wood_button.click_on");
        registerSound("block.cherry_wood_door.close");
        registerSound("block.cherry_wood_door.open");
        registerSound("block.cherry_wood.fall");
        registerSound("block.cherry_wood_fence_gate.close");
        registerSound("block.cherry_wood_fence_gate.open");
        registerSound("block.cherry_wood_hanging_sign.break");
        registerSound("block.cherry_wood_hanging_sign.fall");
        registerSound("block.cherry_wood_hanging_sign.hit");
        registerSound("block.cherry_wood_hanging_sign.place");
        registerSound("block.cherry_wood_hanging_sign.step");
        registerSound("block.cherry_wood.hit");
        registerSound("block.cherry_wood.place");
        registerSound("block.cherry_wood_pressure_plate.click_off");
        registerSound("block.cherry_wood_pressure_plate.click_on");
        registerSound("block.cherry_wood.step");
        registerSound("block.cherry_wood_trapdoor.close");
        registerSound("block.cherry_wood_trapdoor.open");
        registerSound("block.chest.locked");
        registerSound("block.chiseled_bookshelf.break");
        registerSound("block.chiseled_bookshelf.fall");
        registerSound("block.chiseled_bookshelf.hit");
        registerSound("block.chiseled_bookshelf.insert");
        registerSound("block.chiseled_bookshelf.insert.enchanted");
        registerSound("block.chiseled_bookshelf.pickup");
        registerSound("block.chiseled_bookshelf.pickup.enchanted");
        registerSound("block.chiseled_bookshelf.place");
        registerSound("block.chiseled_bookshelf.step");
        registerSound("block.chorus_flower.death");
        registerSound("block.chorus_flower.grow");
        registerSound("block.cobweb.break");
        registerSound("block.cobweb.fall");
        registerSound("block.cobweb.hit");
        registerSound("block.cobweb.place");
        registerSound("block.cobweb.step");
        registerSound("block.comparator.click");
        registerSound("block.composter.empty");
        registerSound("block.composter.fill");
        registerSound("block.composter.fill_success");
        registerSound("block.composter.ready");
        registerSound("block.conduit.activate");
        registerSound("block.conduit.ambient");
        registerSound("block.conduit.ambient.short");
        registerSound("block.conduit.attack_target");
        registerSound("block.conduit.deactivate");
        registerSound("block.copper.break");
        registerSound("block.copper_bulb.break");
        registerSound("block.copper_bulb.fall");
        registerSound("block.copper_bulb.hit");
        registerSound("block.copper_bulb.place");
        registerSound("block.copper_bulb.step");
        registerSound("block.copper_bulb.turn_off");
        registerSound("block.copper_bulb.turn_on");
        registerSound("block.copper_door.close");
        registerSound("block.copper_door.open");
        registerSound("block.copper.fall");
        registerSound("block.copper_grate.break");
        registerSound("block.copper_grate.fall");
        registerSound("block.copper_grate.hit");
        registerSound("block.copper_grate.place");
        registerSound("block.copper_grate.step");
        registerSound("block.copper.hit");
        registerSound("block.copper.place");
        registerSound("block.copper.step");
        registerSound("block.copper_trapdoor.close");
        registerSound("block.copper_trapdoor.open");
        registerSound("block.coral_block.break");
        registerSound("block.coral_block.fall");
        registerSound("block.coral_block.hit");
        registerSound("block.coral_block.place");
        registerSound("block.coral_block.step");
        registerSound("block.crafter.craft");
        registerSound("block.crafter.fail");
        registerSound("block.creaking_heart.break");
        registerSound("block.creaking_heart.fall");
        registerSound("block.creaking_heart.hit");
        registerSound("block.creaking_heart.hurt");
        registerSound("block.creaking_heart.idle");
        registerSound("block.creaking_heart.place");
        registerSound("block.creaking_heart.spawn");
        registerSound("block.creaking_heart.step");
        registerSound("block.crop.break");
        registerSound("block.decorated_pot.break");
        registerSound("block.decorated_pot.fall");
        registerSound("block.decorated_pot.hit");
        registerSound("block.decorated_pot.insert");
        registerSound("block.decorated_pot.insert_fail");
        registerSound("block.decorated_pot.place");
        registerSound("block.decorated_pot.shatter");
        registerSound("block.decorated_pot.step");
        registerSound("block.deepslate.break");
        registerSound("block.deepslate_bricks.break");
        registerSound("block.deepslate_bricks.fall");
        registerSound("block.deepslate_bricks.hit");
        registerSound("block.deepslate_bricks.place");
        registerSound("block.deepslate_bricks.step");
        registerSound("block.deepslate.fall");
        registerSound("block.deepslate.hit");
        registerSound("block.deepslate.place");
        registerSound("block.deepslate.step");
        registerSound("block.deepslate_tiles.break");
        registerSound("block.deepslate_tiles.fall");
        registerSound("block.deepslate_tiles.hit");
        registerSound("block.deepslate_tiles.place");
        registerSound("block.deepslate_tiles.step");
        registerSound("block.dispenser.dispense");
        registerSound("block.dispenser.fail");
        registerSound("block.dispenser.launch");
        registerSound("block.dripstone_block.break");
        registerSound("block.dripstone_block.fall");
        registerSound("block.dripstone_block.hit");
        registerSound("block.dripstone_block.place");
        registerSound("block.dripstone_block.step");
        registerSound("block.enchantment_table.use");
        registerSound("block.ender_chest.close", "block_enderchest_close");
        registerSound("block.ender_chest.open", "block_enderchest_open");
        registerSound("block.end_gateway.spawn");
        registerSound("block.end_portal_frame.fill");
        registerSound("block.end_portal.spawn");
        registerSound("block.fence_gate.close");
        registerSound("block.fence_gate.open");
        registerSound("block.flowering_azalea.break");
        registerSound("block.flowering_azalea.fall");
        registerSound("block.flowering_azalea.hit");
        registerSound("block.flowering_azalea.place");
        registerSound("block.flowering_azalea.step");
        registerSound("block.froglight.break");
        registerSound("block.froglight.fall");
        registerSound("block.froglight.hit");
        registerSound("block.froglight.place");
        registerSound("block.froglight.step");
        registerSound("block.frogspawn.break");
        registerSound("block.frogspawn.fall");
        registerSound("block.frogspawn.hatch");
        registerSound("block.frogspawn.hit");
        registerSound("block.frogspawn.place");
        registerSound("block.frogspawn.step");
        registerSound("block.fungus.break");
        registerSound("block.fungus.fall");
        registerSound("block.fungus.hit");
        registerSound("block.fungus.place");
        registerSound("block.fungus.step");
        registerSound("block.furnace.fire_crackle");
        registerSound("block.gilded_blackstone.break");
        registerSound("block.gilded_blackstone.fall");
        registerSound("block.gilded_blackstone.hit");
        registerSound("block.gilded_blackstone.place");
        registerSound("block.gilded_blackstone.step");
        registerSound("block.glass.fall");
        registerSound("block.glass.hit");
        registerSound("block.glass.place");
        registerSound("block.glass.step");
        registerSound("block.grass.fall");
        registerSound("block.grass.hit");
        registerSound("block.grass.place");
        registerSound("block.gravel.fall");
        registerSound("block.gravel.hit");
        registerSound("block.gravel.place");
        registerSound("block.grindstone.use");
        registerSound("block.growing_plant.crop");
        registerSound("block.hanging_roots.break");
        registerSound("block.hanging_roots.fall");
        registerSound("block.hanging_roots.hit");
        registerSound("block.hanging_roots.place");
        registerSound("block.hanging_roots.step");
        registerSound("block.hanging_sign.break");
        registerSound("block.hanging_sign.fall");
        registerSound("block.hanging_sign.hit");
        registerSound("block.hanging_sign.place");
        registerSound("block.hanging_sign.step");
        registerSound("block.hanging_sign.waxed_interact_fail");
        registerSound("block.heavy_core.break");
        registerSound("block.heavy_core.fall");
        registerSound("block.heavy_core.hit");
        registerSound("block.heavy_core.place");
        registerSound("block.heavy_core.step");
        registerSound("block.honey_block.break");
        registerSound("block.honey_block.fall");
        registerSound("block.honey_block.hit");
        registerSound("block.honey_block.place");
        registerSound("block.honey_block.slide");
        registerSound("block.honey_block.step");
        registerSound("block.iron_door.close");
        registerSound("block.iron_door.open");
        registerSound("block.iron_trapdoor.close");
        registerSound("block.iron_trapdoor.open");
        registerSound("block.ladder.break");
        registerSound("block.ladder.fall");
        registerSound("block.ladder.hit");
        registerSound("block.ladder.place");
        registerSound("block.lantern.break");
        registerSound("block.lantern.fall");
        registerSound("block.lantern.hit");
        registerSound("block.lantern.place");
        registerSound("block.lantern.step");
        registerSound("block.large_amethyst_bud.break");
        registerSound("block.large_amethyst_bud.place");
        registerSound("block.lava.extinguish");
        registerSound("block.lever.click");
        registerSound("block.lodestone.break");
        registerSound("block.lodestone.fall");
        registerSound("block.lodestone.hit");
        registerSound("block.lodestone.place");
        registerSound("block.lodestone.step");
        registerSound("block.mangrove_roots.break");
        registerSound("block.mangrove_roots.fall");
        registerSound("block.mangrove_roots.hit");
        registerSound("block.mangrove_roots.place");
        registerSound("block.mangrove_roots.step");
        registerSound("block.medium_amethyst_bud.break");
        registerSound("block.medium_amethyst_bud.place");
        registerSound("block.metal.break");
        registerSound("block.metal.fall");
        registerSound("block.metal.hit");
        registerSound("block.metal.place");
        registerSound("block.metal.step");
        registerSound("block.moss.break");
        registerSound("block.moss_carpet.break");
        registerSound("block.moss_carpet.fall");
        registerSound("block.moss_carpet.hit");
        registerSound("block.moss_carpet.place");
        registerSound("block.moss_carpet.step");
        registerSound("block.moss.fall");
        registerSound("block.moss.hit");
        registerSound("block.moss.place");
        registerSound("block.moss.step");
        registerSound("block.muddy_mangrove_roots.break");
        registerSound("block.muddy_mangrove_roots.fall");
        registerSound("block.muddy_mangrove_roots.hit");
        registerSound("block.muddy_mangrove_roots.place");
        registerSound("block.muddy_mangrove_roots.step");
        registerSound("block.mud.break");
        registerSound("block.mud_bricks.break");
        registerSound("block.mud_bricks.fall");
        registerSound("block.mud_bricks.hit");
        registerSound("block.mud_bricks.place");
        registerSound("block.mud_bricks.step");
        registerSound("block.mud.fall");
        registerSound("block.mud.hit");
        registerSound("block.mud.place");
        registerSound("block.mud.step");
        registerSound("block.netherite_block.break");
        registerSound("block.netherite_block.fall");
        registerSound("block.netherite_block.hit");
        registerSound("block.netherite_block.place");
        registerSound("block.netherite_block.step");
        registerSound("block.netherrack.break");
        registerSound("block.netherrack.fall");
        registerSound("block.netherrack.hit");
        registerSound("block.netherrack.place");
        registerSound("block.netherrack.step");
        registerSound("block.nether_bricks.break");
        registerSound("block.nether_bricks.fall");
        registerSound("block.nether_bricks.hit");
        registerSound("block.nether_bricks.place");
        registerSound("block.nether_bricks.step");
        registerSound("block.nether_gold_ore.break");
        registerSound("block.nether_gold_ore.fall");
        registerSound("block.nether_gold_ore.hit");
        registerSound("block.nether_gold_ore.place");
        registerSound("block.nether_gold_ore.step");
        registerSound("block.nether_ore.break");
        registerSound("block.nether_ore.fall");
        registerSound("block.nether_ore.hit");
        registerSound("block.nether_ore.place");
        registerSound("block.nether_ore.step");
        registerSound("block.nether_sprouts.break");
        registerSound("block.nether_sprouts.fall");
        registerSound("block.nether_sprouts.hit");
        registerSound("block.nether_sprouts.place");
        registerSound("block.nether_sprouts.step");
        registerSound("block.nether_wart.break");
        registerSound("block.nether_wood.break");
        registerSound("block.nether_wood_button.click_off");
        registerSound("block.nether_wood_button.click_on");
        registerSound("block.nether_wood_door.close");
        registerSound("block.nether_wood_door.open");
        registerSound("block.nether_wood.fall");
        registerSound("block.nether_wood_fence_gate.close");
        registerSound("block.nether_wood_fence_gate.open");
        registerSound("block.nether_wood_hanging_sign.break");
        registerSound("block.nether_wood_hanging_sign.fall");
        registerSound("block.nether_wood_hanging_sign.hit");
        registerSound("block.nether_wood_hanging_sign.place");
        registerSound("block.nether_wood_hanging_sign.step");
        registerSound("block.nether_wood.hit");
        registerSound("block.nether_wood.place");
        registerSound("block.nether_wood_pressure_plate.click_off");
        registerSound("block.nether_wood_pressure_plate.click_on");
        registerSound("block.nether_wood.step");
        registerSound("block.nether_wood_trapdoor.close");
        registerSound("block.nether_wood_trapdoor.open");
        registerSound("block.note_block.banjo");
        registerSound("block.note_block.bit");
        registerSound("block.note_block.cow_bell");
        registerSound("block.note_block.didgeridoo");
        registerSound("block.note_block.imitate.creeper");
        registerSound("block.note_block.imitate.ender_dragon");
        registerSound("block.note_block.imitate.piglin");
        registerSound("block.note_block.imitate.skeleton");
        registerSound("block.note_block.imitate.wither_skeleton");
        registerSound("block.note_block.imitate.zombie");
        registerSound("block.note_block.iron_xylophone");
        registerSound("block.nylium.break");
        registerSound("block.nylium.fall");
        registerSound("block.nylium.hit");
        registerSound("block.nylium.place");
        registerSound("block.nylium.step");
        registerSound("block.packed_mud.break");
        registerSound("block.packed_mud.fall");
        registerSound("block.packed_mud.hit");
        registerSound("block.packed_mud.place");
        registerSound("block.packed_mud.step");
        registerSound("block.pale_hanging_moss.idle");
        registerSound("block.pink_petals.break");
        registerSound("block.pink_petals.fall");
        registerSound("block.pink_petals.hit");
        registerSound("block.pink_petals.place");
        registerSound("block.pink_petals.step");
        registerSound("block.pointed_dripstone.break");
        registerSound("block.pointed_dripstone.drip_lava");
        registerSound("block.pointed_dripstone.drip_lava_into_cauldron");
        registerSound("block.pointed_dripstone.drip_water");
        registerSound("block.pointed_dripstone.drip_water_into_cauldron");
        registerSound("block.pointed_dripstone.fall");
        registerSound("block.pointed_dripstone.hit");
        registerSound("block.pointed_dripstone.land");
        registerSound("block.pointed_dripstone.place");
        registerSound("block.pointed_dripstone.step");
        registerSound("block.polished_deepslate.break");
        registerSound("block.polished_deepslate.fall");
        registerSound("block.polished_deepslate.hit");
        registerSound("block.polished_deepslate.place");
        registerSound("block.polished_deepslate.step");
        registerSound("block.polished_tuff.break");
        registerSound("block.polished_tuff.fall");
        registerSound("block.polished_tuff.hit");
        registerSound("block.polished_tuff.place");
        registerSound("block.polished_tuff.step");
        registerSound("block.powder_snow.break");
        registerSound("block.powder_snow.fall");
        registerSound("block.powder_snow.hit");
        registerSound("block.powder_snow.place");
        registerSound("block.powder_snow.step");
        registerSound("block.pumpkin.carve");
        registerSound("block.redstone_torch.burnout");
        registerSound("block.respawn_anchor.ambient");
        registerSound("block.respawn_anchor.charge");
        registerSound("block.respawn_anchor.deplete");
        registerSound("block.respawn_anchor.set_spawn");
        registerSound("block.rooted_dirt.break");
        registerSound("block.rooted_dirt.fall");
        registerSound("block.rooted_dirt.hit");
        registerSound("block.rooted_dirt.place");
        registerSound("block.rooted_dirt.step");
        registerSound("block.roots.break");
        registerSound("block.roots.fall");
        registerSound("block.roots.hit");
        registerSound("block.roots.place");
        registerSound("block.roots.step");
        registerSound("block.sand.fall");
        registerSound("block.sand.hit");
        registerSound("block.sand.place");
        registerSound("block.scaffolding.break");
        registerSound("block.scaffolding.fall");
        registerSound("block.scaffolding.hit");
        registerSound("block.scaffolding.place");
        registerSound("block.scaffolding.step");
        registerSound("block.sculk.break");
        registerSound("block.sculk_catalyst.bloom");
        registerSound("block.sculk_catalyst.break");
        registerSound("block.sculk_catalyst.fall");
        registerSound("block.sculk_catalyst.hit");
        registerSound("block.sculk_catalyst.place");
        registerSound("block.sculk_catalyst.step");
        registerSound("block.sculk.charge");
        registerSound("block.sculk.fall");
        registerSound("block.sculk.hit");
        registerSound("block.sculk.place");
        registerSound("block.sculk_sensor.break");
        registerSound("block.sculk_sensor.clicking");
        registerSound("block.sculk_sensor.clicking_stop");
        registerSound("block.sculk_sensor.fall");
        registerSound("block.sculk_sensor.hit");
        registerSound("block.sculk_sensor.place");
        registerSound("block.sculk_sensor.step");
        registerSound("block.sculk_shrieker.break");
        registerSound("block.sculk_shrieker.fall");
        registerSound("block.sculk_shrieker.hit");
        registerSound("block.sculk_shrieker.place");
        registerSound("block.sculk_shrieker.shriek");
        registerSound("block.sculk_shrieker.step");
        registerSound("block.sculk.spread");
        registerSound("block.sculk.step");
        registerSound("block.sculk_vein.break");
        registerSound("block.sculk_vein.fall");
        registerSound("block.sculk_vein.hit");
        registerSound("block.sculk_vein.place");
        registerSound("block.sculk_vein.step");
        registerSound("block.shroomlight.break");
        registerSound("block.shroomlight.fall");
        registerSound("block.shroomlight.hit");
        registerSound("block.shroomlight.place");
        registerSound("block.shroomlight.step");
        registerSound("block.shulker_box.close");
        registerSound("block.shulker_box.open");
        registerSound("block.sign.waxed_interact_fail");
        registerSound("block.small_amethyst_bud.break");
        registerSound("block.small_amethyst_bud.place");
        registerSound("block.small_dripleaf.break");
        registerSound("block.small_dripleaf.fall");
        registerSound("block.small_dripleaf.hit");
        registerSound("block.small_dripleaf.place");
        registerSound("block.small_dripleaf.step");
        registerSound("block.smithing_table.use");
        registerSound("block.smoker.smoke");
        registerSound("block.sniffer_egg.crack");
        registerSound("block.sniffer_egg.hatch");
        registerSound("block.sniffer_egg.plop");
        registerSound("block.snow.fall");
        registerSound("block.snow.hit");
        registerSound("block.snow.place");
        registerSound("block.soul_sand.break");
        registerSound("block.soul_sand.fall");
        registerSound("block.soul_sand.hit");
        registerSound("block.soul_sand.place");
        registerSound("block.soul_sand.step");
        registerSound("block.soul_soil.break");
        registerSound("block.soul_soil.fall");
        registerSound("block.soul_soil.hit");
        registerSound("block.soul_soil.place");
        registerSound("block.soul_soil.step");
        registerSound("block.spawner.break");
        registerSound("block.spawner.fall");
        registerSound("block.spawner.hit");
        registerSound("block.spawner.place");
        registerSound("block.spawner.step");
        registerSound("block.sponge.absorb");
        registerSound("block.sponge.break");
        registerSound("block.sponge.fall");
        registerSound("block.sponge.hit");
        registerSound("block.sponge.place");
        registerSound("block.sponge.step");
        registerSound("block.spore_blossom.break");
        registerSound("block.spore_blossom.fall");
        registerSound("block.spore_blossom.hit");
        registerSound("block.spore_blossom.place");
        registerSound("block.spore_blossom.step");
        registerSound("block.stem.break");
        registerSound("block.stem.fall");
        registerSound("block.stem.hit");
        registerSound("block.stem.place");
        registerSound("block.stem.step");
        registerSound("block.stone_button.click_off");
        registerSound("block.stone_button.click_on");
        registerSound("block.stone.fall");
        registerSound("block.stone.hit");
        registerSound("block.stone.place");
        registerSound("block.suspicious_gravel.break");
        registerSound("block.suspicious_gravel.fall");
        registerSound("block.suspicious_gravel.hit");
        registerSound("block.suspicious_gravel.place");
        registerSound("block.suspicious_gravel.step");
        registerSound("block.suspicious_sand.break");
        registerSound("block.suspicious_sand.fall");
        registerSound("block.suspicious_sand.hit");
        registerSound("block.suspicious_sand.place");
        registerSound("block.suspicious_sand.step");
        registerSound("block.sweet_berry_bush.break");
        registerSound("block.sweet_berry_bush.place");
        registerSound("block.trial_spawner.about_to_spawn_item");
        registerSound("block.trial_spawner.ambient");
        registerSound("block.trial_spawner.ambient_ominous");
        registerSound("block.trial_spawner.break");
        registerSound("block.trial_spawner.close_shutter");
        registerSound("block.trial_spawner.detect_player");
        registerSound("block.trial_spawner.eject_item");
        registerSound("block.trial_spawner.fall");
        registerSound("block.trial_spawner.hit");
        registerSound("block.trial_spawner.ominous_activate");
        registerSound("block.trial_spawner.open_shutter");
        registerSound("block.trial_spawner.place");
        registerSound("block.trial_spawner.spawn_item");
        registerSound("block.trial_spawner.spawn_item_begin");
        registerSound("block.trial_spawner.spawn_mob");
        registerSound("block.trial_spawner.step");
        registerSound("block.tripwire.attach");
        registerSound("block.tripwire.click_off");
        registerSound("block.tripwire.click_on");
        registerSound("block.tripwire.detach");
        registerSound("block.tuff.break");
        registerSound("block.tuff_bricks.break");
        registerSound("block.tuff_bricks.fall");
        registerSound("block.tuff_bricks.hit");
        registerSound("block.tuff_bricks.place");
        registerSound("block.tuff_bricks.step");
        registerSound("block.tuff.fall");
        registerSound("block.tuff.hit");
        registerSound("block.tuff.place");
        registerSound("block.tuff.step");
        registerSound("block.vault.activate");
        registerSound("block.vault.ambient");
        registerSound("block.vault.break");
        registerSound("block.vault.close_shutter");
        registerSound("block.vault.deactivate");
        registerSound("block.vault.eject_item");
        registerSound("block.vault.fall");
        registerSound("block.vault.hit");
        registerSound("block.vault.insert_item");
        registerSound("block.vault.insert_item_fail");
        registerSound("block.vault.open_shutter");
        registerSound("block.vault.place");
        registerSound("block.vault.reject_rewarded_player");
        registerSound("block.vault.step");
        registerSound("block.vine.break");
        registerSound("block.vine.fall");
        registerSound("block.vine.hit");
        registerSound("block.vine.place");
        registerSound("block.vine.step");
        registerSound("block.wart_block.break");
        registerSound("block.wart_block.fall");
        registerSound("block.wart_block.hit");
        registerSound("block.wart_block.place");
        registerSound("block.wart_block.step");
        registerSound("block.weeping_vines.break");
        registerSound("block.weeping_vines.fall");
        registerSound("block.weeping_vines.hit");
        registerSound("block.weeping_vines.place");
        registerSound("block.weeping_vines.step");
        registerSound("block.wet_grass.break");
        registerSound("block.wet_grass.fall");
        registerSound("block.wet_grass.hit");
        registerSound("block.wet_sponge.break");
        registerSound("block.wet_sponge.dries");
        registerSound("block.wet_sponge.fall");
        registerSound("block.wet_sponge.hit");
        registerSound("block.wet_sponge.place");
        registerSound("block.wet_sponge.step");
        registerSound("block.wooden_trapdoor.close");
        registerSound("block.wooden_trapdoor.open");
        registerSound("block.wood.fall");
        registerSound("block.wood.hit");
        registerSound("block.wood.place");
        registerSound("block.wool.fall", "block_wool_fall", "block_cloth_fall");
        registerSound("enchant.thorns.hit");
        registerSound("entity.allay.ambient_without_item");
        registerSound("entity.allay.ambient_with_item");
        registerSound("entity.allay.death");
        registerSound("entity.allay.hurt");
        registerSound("entity.allay.item_given");
        registerSound("entity.allay.item_taken");
        registerSound("entity.allay.item_thrown");
        registerSound("entity.armadillo.ambient");
        registerSound("entity.armadillo.brush");
        registerSound("entity.armadillo.death");
        registerSound("entity.armadillo.eat");
        registerSound("entity.armadillo.hurt");
        registerSound("entity.armadillo.hurt_reduced");
        registerSound("entity.armadillo.land");
        registerSound("entity.armadillo.peek");
        registerSound("entity.armadillo.roll");
        registerSound("entity.armadillo.scute_drop");
        registerSound("entity.armadillo.step");
        registerSound("entity.armadillo.unroll_finish");
        registerSound("entity.armadillo.unroll_start");
        registerSound("entity.axolotl.attack");
        registerSound("entity.axolotl.death");
        registerSound("entity.axolotl.hurt");
        registerSound("entity.axolotl.idle_air");
        registerSound("entity.axolotl.idle_water");
        registerSound("entity.axolotl.splash");
        registerSound("entity.axolotl.swim");
        registerSound("entity.bee.death");
        registerSound("entity.bee.hurt");
        registerSound("entity.bee.loop");
        registerSound("entity.bee.loop_aggressive");
        registerSound("entity.bee.pollinate");
        registerSound("entity.bee.sting");
        registerSound("entity.blaze.burn");
        registerSound("entity.blaze.shoot");
        registerSound("entity.boat.paddle_land");
        registerSound("entity.boat.paddle_water");
        registerSound("entity.bogged.ambient");
        registerSound("entity.bogged.death");
        registerSound("entity.bogged.hurt");
        registerSound("entity.bogged.shear");
        registerSound("entity.bogged.step");
        registerSound("entity.breeze.charge");
        registerSound("entity.breeze.death");
        registerSound("entity.breeze.deflect");
        registerSound("entity.breeze.hurt");
        registerSound("entity.breeze.idle_air");
        registerSound("entity.breeze.idle_ground");
        registerSound("entity.breeze.inhale");
        registerSound("entity.breeze.jump");
        registerSound("entity.breeze.land");
        registerSound("entity.breeze.shoot");
        registerSound("entity.breeze.slide");
        registerSound("entity.breeze.whirl");
        registerSound("entity.breeze.wind_burst");
        registerSound("entity.camel.ambient");
        registerSound("entity.camel.dash");
        registerSound("entity.camel.dash_ready");
        registerSound("entity.camel.death");
        registerSound("entity.camel.eat");
        registerSound("entity.camel.hurt");
        registerSound("entity.camel.saddle");
        registerSound("entity.camel.sit");
        registerSound("entity.camel.stand");
        registerSound("entity.camel.step");
        registerSound("entity.camel.step_sand");
        registerSound("entity.cat.beg_for_food");
        registerSound("entity.cat.death");
        registerSound("entity.cat.stray_ambient");
        registerSound("entity.chicken.death");
        registerSound("entity.cod.ambient");
        registerSound("entity.cod.death");
        registerSound("entity.cod.flop");
        registerSound("entity.cod.hurt");
        registerSound("entity.cow.death");
        registerSound("entity.cow.milk");
        registerSound("entity.creaking.activate");
        registerSound("entity.creaking.ambient");
        registerSound("entity.creaking.attack");
        registerSound("entity.creaking.deactivate");
        registerSound("entity.creaking.death");
        registerSound("entity.creaking.freeze");
        registerSound("entity.creaking.spawn");
        registerSound("entity.creaking.step");
        registerSound("entity.creaking.sway");
        registerSound("entity.creaking.unfreeze");
        registerSound("entity.creeper.hurt");
        registerSound("entity.dolphin.ambient");
        registerSound("entity.dolphin.ambient_water");
        registerSound("entity.dolphin.attack");
        registerSound("entity.dolphin.death");
        registerSound("entity.dolphin.eat");
        registerSound("entity.dolphin.hurt");
        registerSound("entity.dolphin.jump");
        registerSound("entity.dolphin.play");
        registerSound("entity.dolphin.splash");
        registerSound("entity.dolphin.swim");
        registerSound("entity.donkey.chest");
        registerSound("entity.donkey.eat");
        registerSound("entity.donkey.jump");
        registerSound("entity.drowned.ambient");
        registerSound("entity.drowned.ambient_water");
        registerSound("entity.drowned.death");
        registerSound("entity.drowned.death_water");
        registerSound("entity.drowned.hurt");
        registerSound("entity.drowned.hurt_water");
        registerSound("entity.drowned.shoot");
        registerSound("entity.drowned.step");
        registerSound("entity.drowned.swim");
        registerSound("entity.egg.throw");
        registerSound("entity.elder_guardian.ambient");
        registerSound("entity.elder_guardian.ambient_land");
        registerSound("entity.elder_guardian.curse");
        registerSound("entity.elder_guardian.death");
        registerSound("entity.elder_guardian.death_land");
        registerSound("entity.elder_guardian.flop");
        registerSound("entity.elder_guardian.hurt");
        registerSound("entity.elder_guardian.hurt_land");
        registerSound("entity.endermite.ambient");
        registerSound("entity.endermite.death");
        registerSound("entity.endermite.hurt");
        registerSound("entity.endermite.step");
        registerSound("entity.ender_eye.death", "entity_ender_eye_death", "entity_endereye_death");
        registerSound("entity.evoker.celebrate");
        registerSound("entity.experience_bottle.throw");
        registerSound("entity.firework_rocket.shoot", "entity_firework_shoot");
        registerSound("entity.fishing_bobber.retrieve", "entity_bobber_retrieve");
        registerSound("entity.fish.swim");
        registerSound("entity.fox.aggro");
        registerSound("entity.fox.ambient");
        registerSound("entity.fox.bite");
        registerSound("entity.fox.death");
        registerSound("entity.fox.eat");
        registerSound("entity.fox.hurt");
        registerSound("entity.fox.screech");
        registerSound("entity.fox.sleep");
        registerSound("entity.fox.sniff");
        registerSound("entity.fox.spit");
        registerSound("entity.fox.teleport");
        registerSound("entity.frog.ambient");
        registerSound("entity.frog.death");
        registerSound("entity.frog.eat");
        registerSound("entity.frog.hurt");
        registerSound("entity.frog.lay_spawn");
        registerSound("entity.frog.long_jump");
        registerSound("entity.frog.step");
        registerSound("entity.frog.tongue");
        registerSound("entity.generic.burn");
        registerSound("entity.generic.death");
        registerSound("entity.generic.extinguish_fire");
        registerSound("entity.generic.hurt");
        registerSound("entity.glow_item_frame.add_item");
        registerSound("entity.glow_item_frame.break");
        registerSound("entity.glow_item_frame.place");
        registerSound("entity.glow_item_frame.remove_item");
        registerSound("entity.glow_item_frame.rotate_item");
        registerSound("entity.glow_squid.ambient");
        registerSound("entity.glow_squid.death");
        registerSound("entity.glow_squid.hurt");
        registerSound("entity.glow_squid.squirt");
        registerSound("entity.goat.ambient");
        registerSound("entity.goat.death");
        registerSound("entity.goat.eat");
        registerSound("entity.goat.horn_break");
        registerSound("entity.goat.hurt");
        registerSound("entity.goat.long_jump");
        registerSound("entity.goat.milk");
        registerSound("entity.goat.prepare_ram");
        registerSound("entity.goat.ram_impact");
        registerSound("entity.goat.screaming.ambient");
        registerSound("entity.goat.screaming.death");
        registerSound("entity.goat.screaming.eat");
        registerSound("entity.goat.screaming.hurt");
        registerSound("entity.goat.screaming.long_jump");
        registerSound("entity.goat.screaming.milk");
        registerSound("entity.goat.screaming.prepare_ram");
        registerSound("entity.goat.screaming.ram_impact");
        registerSound("entity.goat.step");
        registerSound("entity.guardian.ambient");
        registerSound("entity.guardian.ambient_land");
        registerSound("entity.guardian.attack");
        registerSound("entity.guardian.death");
        registerSound("entity.guardian.death_land");
        registerSound("entity.guardian.flop");
        registerSound("entity.guardian.hurt");
        registerSound("entity.guardian.hurt_land");
        registerSound("entity.hoglin.ambient");
        registerSound("entity.hoglin.angry");
        registerSound("entity.hoglin.attack");
        registerSound("entity.hoglin.converted_to_zombified");
        registerSound("entity.hoglin.death");
        registerSound("entity.hoglin.hurt");
        registerSound("entity.hoglin.retreat");
        registerSound("entity.hoglin.step");
        registerSound("entity.hostile.death");
        registerSound("entity.hostile.hurt");
        registerSound("entity.husk.ambient");
        registerSound("entity.husk.converted_to_zombie");
        registerSound("entity.husk.death");
        registerSound("entity.husk.hurt");
        registerSound("entity.husk.step");
        registerSound("entity.iron_golem.damage");
        registerSound("entity.iron_golem.repair");
        registerSound("entity.llama.ambient");
        registerSound("entity.llama.angry");
        registerSound("entity.llama.chest");
        registerSound("entity.llama.death");
        registerSound("entity.llama.eat");
        registerSound("entity.llama.hurt");
        registerSound("entity.llama.spit");
        registerSound("entity.llama.step");
        registerSound("entity.llama.swag");
        registerSound("entity.minecart.inside.underwater");
        registerSound("entity.mooshroom.convert");
        registerSound("entity.mooshroom.eat");
        registerSound("entity.mooshroom.milk");
        registerSound("entity.mooshroom.shear");
        registerSound("entity.mooshroom.suspicious_milk");
        registerSound("entity.mule.ambient");
        registerSound("entity.mule.angry");
        registerSound("entity.mule.eat");
        registerSound("entity.mule.jump");
        registerSound("entity.ocelot.ambient");
        registerSound("entity.ocelot.death");
        registerSound("entity.ocelot.hurt");
        registerSound("entity.painting.break");
        registerSound("entity.painting.place");
        registerSound("entity.panda.aggressive_ambient");
        registerSound("entity.panda.ambient");
        registerSound("entity.panda.bite");
        registerSound("entity.panda.cant_breed");
        registerSound("entity.panda.death");
        registerSound("entity.panda.eat");
        registerSound("entity.panda.hurt");
        registerSound("entity.panda.pre_sneeze");
        registerSound("entity.panda.sneeze");
        registerSound("entity.panda.step");
        registerSound("entity.panda.worried_ambient");
        registerSound("entity.parrot.ambient");
        registerSound("entity.parrot.death");
        registerSound("entity.parrot.eat");
        registerSound("entity.parrot.fly");
        registerSound("entity.parrot.hurt");
        registerSound("entity.parrot.imitate.blaze");
        registerSound("entity.parrot.imitate.bogged");
        registerSound("entity.parrot.imitate.breeze");
        registerSound("entity.parrot.imitate.creaking");
        registerSound("entity.parrot.imitate.creeper");
        registerSound("entity.parrot.imitate.drowned");
        registerSound("entity.parrot.imitate.elder_guardian");
        registerSound("entity.parrot.imitate.endermite");
        registerSound("entity.parrot.imitate.ender_dragon", "entity_parrot_imitate_enderdragon");
        registerSound("entity.parrot.imitate.evoker", "entity_parrot_imitate_evocation_illager");
        registerSound("entity.parrot.imitate.ghast");
        registerSound("entity.parrot.imitate.guardian");
        registerSound("entity.parrot.imitate.hoglin");
        registerSound("entity.parrot.imitate.husk");
        registerSound("entity.parrot.imitate.illusioner", "entity_parrot_imitate_illusion_illager");
        registerSound("entity.parrot.imitate.magma_cube", "entity_parrot_imitate_magmacube");
        registerSound("entity.parrot.imitate.phantom");
        registerSound("entity.parrot.imitate.piglin", "entity_parrot_imitate_zombie_pigman");
        registerSound("entity.parrot.imitate.piglin_brute");
        registerSound("entity.parrot.imitate.pillager");
        registerSound("entity.parrot.imitate.ravager");
        registerSound("entity.parrot.imitate.shulker");
        registerSound("entity.parrot.imitate.silverfish");
        registerSound("entity.parrot.imitate.skeleton");
        registerSound("entity.parrot.imitate.slime");
        registerSound("entity.parrot.imitate.spider");
        registerSound("entity.parrot.imitate.stray");
        registerSound("entity.parrot.imitate.vex");
        registerSound("entity.parrot.imitate.vindicator", "entity_parrot_imitate_vindication_illager");
        registerSound("entity.parrot.imitate.warden");
        registerSound("entity.parrot.imitate.witch");
        registerSound("entity.parrot.imitate.wither");
        registerSound("entity.parrot.imitate.wither_skeleton");
        registerSound("entity.parrot.imitate.zoglin");
        registerSound("entity.parrot.imitate.zombie");
        registerSound("entity.parrot.imitate.zombie_villager");
        registerSound("entity.parrot.step");
        registerSound("entity.phantom.ambient");
        registerSound("entity.phantom.bite");
        registerSound("entity.phantom.death");
        registerSound("entity.phantom.flap");
        registerSound("entity.phantom.hurt");
        registerSound("entity.phantom.swoop");
        registerSound("entity.piglin.admiring_item");
        registerSound("entity.piglin.ambient");
        registerSound("entity.piglin.angry");
        registerSound("entity.piglin_brute.ambient");
        registerSound("entity.piglin_brute.angry");
        registerSound("entity.piglin_brute.converted_to_zombified");
        registerSound("entity.piglin_brute.death");
        registerSound("entity.piglin_brute.hurt");
        registerSound("entity.piglin_brute.step");
        registerSound("entity.piglin.celebrate");
        registerSound("entity.piglin.converted_to_zombified");
        registerSound("entity.piglin.death");
        registerSound("entity.piglin.hurt");
        registerSound("entity.piglin.jealous");
        registerSound("entity.piglin.retreat");
        registerSound("entity.piglin.step");
        registerSound("entity.pig.hurt");
        registerSound("entity.pillager.ambient");
        registerSound("entity.pillager.celebrate");
        registerSound("entity.pillager.death");
        registerSound("entity.pillager.hurt");
        registerSound("entity.player.attack.crit");
        registerSound("entity.player.attack.knockback");
        registerSound("entity.player.attack.nodamage");
        registerSound("entity.player.attack.sweep");
        registerSound("entity.player.attack.weak");
        registerSound("entity.player.breath");
        registerSound("entity.player.death");
        registerSound("entity.player.hurt_drown");
        registerSound("entity.player.hurt_freeze");
        registerSound("entity.player.hurt_on_fire");
        registerSound("entity.player.hurt_sweet_berry_bush");
        registerSound("entity.player.teleport");
        registerSound("entity.polar_bear.ambient");
        registerSound("entity.polar_bear.death");
        registerSound("entity.polar_bear.hurt");
        registerSound("entity.polar_bear.step");
        registerSound("entity.polar_bear.warning");
        registerSound("entity.puffer_fish.ambient");
        registerSound("entity.puffer_fish.blow_out");
        registerSound("entity.puffer_fish.blow_up");
        registerSound("entity.puffer_fish.death");
        registerSound("entity.puffer_fish.flop");
        registerSound("entity.puffer_fish.hurt");
        registerSound("entity.puffer_fish.sting");
        registerSound("entity.rabbit.ambient");
        registerSound("entity.rabbit.attack");
        registerSound("entity.rabbit.death");
        registerSound("entity.rabbit.hurt");
        registerSound("entity.rabbit.jump");
        registerSound("entity.ravager.ambient");
        registerSound("entity.ravager.attack");
        registerSound("entity.ravager.celebrate");
        registerSound("entity.ravager.death");
        registerSound("entity.ravager.hurt");
        registerSound("entity.ravager.roar");
        registerSound("entity.ravager.step");
        registerSound("entity.ravager.stunned");
        registerSound("entity.salmon.ambient");
        registerSound("entity.salmon.death");
        registerSound("entity.salmon.flop");
        registerSound("entity.sheep.death");
        registerSound("entity.sheep.hurt");
        registerSound("entity.shulker.ambient");
        registerSound("entity.shulker_bullet.hit");
        registerSound("entity.shulker_bullet.hurt");
        registerSound("entity.shulker.close");
        registerSound("entity.shulker.death");
        registerSound("entity.shulker.hurt");
        registerSound("entity.shulker.hurt_closed");
        registerSound("entity.shulker.open");
        registerSound("entity.shulker.shoot");
        registerSound("entity.shulker.teleport");
        registerSound("entity.skeleton.converted_to_stray");
        registerSound("entity.skeleton_horse.ambient_water");
        registerSound("entity.skeleton_horse.gallop_water");
        registerSound("entity.skeleton_horse.jump_water");
        registerSound("entity.skeleton_horse.step_water");
        registerSound("entity.skeleton_horse.swim");
        registerSound("entity.skeleton.shoot");
        registerSound("entity.slime.death", "entity_small_slime_death");
        registerSound("entity.slime.death_small", "entity_small_slime_death");
        registerSound("entity.slime.hurt");
        registerSound("entity.sniffer.death");
        registerSound("entity.sniffer.digging");
        registerSound("entity.sniffer.digging_stop");
        registerSound("entity.sniffer.drop_seed");
        registerSound("entity.sniffer.eat");
        registerSound("entity.sniffer.happy");
        registerSound("entity.sniffer.hurt");
        registerSound("entity.sniffer.idle");
        registerSound("entity.sniffer.scenting");
        registerSound("entity.sniffer.searching");
        registerSound("entity.sniffer.sniffing");
        registerSound("entity.sniffer.step");
        registerSound("entity.snowball.throw");
        registerSound("entity.spider.hurt");
        registerSound("entity.splash_potion.break");
        registerSound("entity.splash_potion.throw");
        registerSound("entity.squid.ambient");
        registerSound("entity.squid.death");
        registerSound("entity.squid.hurt");
        registerSound("entity.squid.squirt");
        registerSound("entity.stray.ambient");
        registerSound("entity.stray.death");
        registerSound("entity.stray.hurt");
        registerSound("entity.stray.step");
        registerSound("entity.strider.ambient");
        registerSound("entity.strider.death");
        registerSound("entity.strider.eat");
        registerSound("entity.strider.happy");
        registerSound("entity.strider.hurt");
        registerSound("entity.strider.retreat");
        registerSound("entity.strider.saddle");
        registerSound("entity.strider.step");
        registerSound("entity.strider.step_lava");
        registerSound("entity.tadpole.death");
        registerSound("entity.tadpole.flop");
        registerSound("entity.tadpole.grow_up");
        registerSound("entity.tadpole.hurt");
        registerSound("entity.tropical_fish.ambient");
        registerSound("entity.tropical_fish.death");
        registerSound("entity.tropical_fish.hurt");
        registerSound("entity.turtle.ambient_land");
        registerSound("entity.turtle.death");
        registerSound("entity.turtle.death_baby");
        registerSound("entity.turtle.egg_break");
        registerSound("entity.turtle.egg_crack");
        registerSound("entity.turtle.egg_hatch");
        registerSound("entity.turtle.hurt");
        registerSound("entity.turtle.hurt_baby");
        registerSound("entity.turtle.lay_egg");
        registerSound("entity.turtle.shamble");
        registerSound("entity.turtle.shamble_baby");
        registerSound("entity.turtle.swim");
        registerSound("entity.vex.ambient");
        registerSound("entity.vex.charge");
        registerSound("entity.vex.death");
        registerSound("entity.vex.hurt");
        registerSound("entity.villager.celebrate");
        registerSound("entity.villager.work_armorer");
        registerSound("entity.villager.work_butcher");
        registerSound("entity.villager.work_cartographer");
        registerSound("entity.villager.work_cleric");
        registerSound("entity.villager.work_farmer");
        registerSound("entity.villager.work_fisherman");
        registerSound("entity.villager.work_fletcher");
        registerSound("entity.villager.work_leatherworker");
        registerSound("entity.villager.work_librarian");
        registerSound("entity.villager.work_mason");
        registerSound("entity.villager.work_shepherd");
        registerSound("entity.villager.work_toolsmith");
        registerSound("entity.villager.work_weaponsmith");
        registerSound("entity.vindicator.celebrate");
        registerSound("entity.wandering_trader.ambient");
        registerSound("entity.wandering_trader.death");
        registerSound("entity.wandering_trader.disappeared");
        registerSound("entity.wandering_trader.drink_milk");
        registerSound("entity.wandering_trader.drink_potion");
        registerSound("entity.wandering_trader.hurt");
        registerSound("entity.wandering_trader.no");
        registerSound("entity.wandering_trader.reappeared");
        registerSound("entity.wandering_trader.trade");
        registerSound("entity.wandering_trader.yes");
        registerSound("entity.warden.agitated");
        registerSound("entity.warden.ambient");
        registerSound("entity.warden.angry");
        registerSound("entity.warden.attack_impact");
        registerSound("entity.warden.death");
        registerSound("entity.warden.dig");
        registerSound("entity.warden.emerge");
        registerSound("entity.warden.heartbeat");
        registerSound("entity.warden.hurt");
        registerSound("entity.warden.listening");
        registerSound("entity.warden.listening_angry");
        registerSound("entity.warden.nearby_close");
        registerSound("entity.warden.nearby_closer");
        registerSound("entity.warden.nearby_closest");
        registerSound("entity.warden.roar");
        registerSound("entity.warden.sniff");
        registerSound("entity.warden.sonic_boom");
        registerSound("entity.warden.sonic_charge");
        registerSound("entity.warden.step");
        registerSound("entity.warden.tendril_clicks");
        registerSound("entity.wind_charge.throw");
        registerSound("entity.witch.ambient");
        registerSound("entity.witch.celebrate");
        registerSound("entity.witch.death");
        registerSound("entity.witch.drink");
        registerSound("entity.witch.hurt");
        registerSound("entity.witch.throw");
        registerSound("entity.wither.break_block");
        registerSound("entity.wither_skeleton.ambient");
        registerSound("entity.wither_skeleton.death");
        registerSound("entity.wither_skeleton.hurt");
        registerSound("entity.wither_skeleton.step");
        registerSound("entity.zoglin.ambient");
        registerSound("entity.zoglin.angry");
        registerSound("entity.zoglin.attack");
        registerSound("entity.zoglin.death");
        registerSound("entity.zoglin.hurt");
        registerSound("entity.zoglin.step");
        registerSound("entity.zombie.converted_to_drowned");
        registerSound("entity.zombie.destroy_egg");
        registerSound("entity.zombie_villager.ambient");
        registerSound("entity.zombie_villager.death");
        registerSound("entity.zombie_villager.hurt");
        registerSound("entity.zombie_villager.step");
        registerSound("event.mob_effect.bad_omen");
        registerSound("event.mob_effect.raid_omen");
        registerSound("event.mob_effect.trial_omen");
        registerSound("event.raid.horn");
        registerSound("intentionally_empty");
        registerSound("item.armor.equip_chain");
        registerSound("item.armor.equip_diamond");
        registerSound("item.armor.equip_elytra");
        registerSound("item.armor.equip_generic");
        registerSound("item.armor.equip_gold");
        registerSound("item.armor.equip_iron");
        registerSound("item.armor.equip_leather");
        registerSound("item.armor.equip_netherite");
        registerSound("item.armor.equip_turtle");
        registerSound("item.armor.equip_wolf");
        registerSound("item.armor.unequip_wolf");
        registerSound("item.axe.scrape");
        registerSound("item.axe.strip");
        registerSound("item.axe.wax_off");
        registerSound("item.bone_meal.use");
        registerSound("item.book.page_turn");
        registerSound("item.book.put");
        registerSound("item.bottle.empty");
        registerSound("item.bottle.fill");
        registerSound("item.bottle.fill_dragonbreath");
        registerSound("item.brush.brushing.generic");
        registerSound("item.brush.brushing.gravel");
        registerSound("item.brush.brushing.gravel.complete");
        registerSound("item.brush.brushing.sand");
        registerSound("item.brush.brushing.sand.complete");
        registerSound("item.bucket.empty");
        registerSound("item.bucket.empty_axolotl");
        registerSound("item.bucket.empty_fish");
        registerSound("item.bucket.empty_lava");
        registerSound("item.bucket.empty_powder_snow");
        registerSound("item.bucket.empty_tadpole");
        registerSound("item.bucket.fill");
        registerSound("item.bucket.fill_axolotl");
        registerSound("item.bucket.fill_fish");
        registerSound("item.bucket.fill_lava");
        registerSound("item.bucket.fill_powder_snow");
        registerSound("item.bucket.fill_tadpole");
        registerSound("item.bundle.drop_contents");
        registerSound("item.bundle.insert");
        registerSound("item.bundle.insert_fail");
        registerSound("item.bundle.remove_one");
        registerSound("item.chorus_fruit.teleport");
        registerSound("item.crop.plant");
        registerSound("item.crossbow.hit");
        registerSound("item.crossbow.loading_end");
        registerSound("item.crossbow.loading_middle");
        registerSound("item.crossbow.loading_start");
        registerSound("item.crossbow.quick_charge_1");
        registerSound("item.crossbow.quick_charge_2");
        registerSound("item.crossbow.quick_charge_3");
        registerSound("item.crossbow.shoot");
        registerSound("item.dye.use");
        registerSound("item.elytra.flying");
        registerSound("item.firecharge.use");
        registerSound("item.glow_ink_sac.use");
        registerSound("item.goat_horn.sound.0");
        registerSound("item.goat_horn.sound.1");
        registerSound("item.goat_horn.sound.2");
        registerSound("item.goat_horn.sound.3");
        registerSound("item.goat_horn.sound.4");
        registerSound("item.goat_horn.sound.5");
        registerSound("item.goat_horn.sound.6");
        registerSound("item.goat_horn.sound.7");
        registerSound("item.hoe.till");
        registerSound("item.honeycomb.wax_on");
        registerSound("item.honey_bottle.drink");
        registerSound("item.ink_sac.use");
        registerSound("item.lodestone_compass.lock");
        registerSound("item.mace.smash_air");
        registerSound("item.mace.smash_ground");
        registerSound("item.mace.smash_ground_heavy");
        registerSound("item.nether_wart.plant");
        registerSound("item.ominous_bottle.dispose");
        registerSound("item.shield.block");
        registerSound("item.shield.break");
        registerSound("item.shovel.flatten");
        registerSound("item.spyglass.stop_using");
        registerSound("item.spyglass.use");
        registerSound("item.totem.use");
        registerSound("item.trident.hit");
        registerSound("item.trident.hit_ground");
        registerSound("item.trident.return");
        registerSound("item.trident.riptide_1");
        registerSound("item.trident.throw");
        registerSound("item.trident.thunder");
        registerSound("item.wolf_armor.break");
        registerSound("item.wolf_armor.crack");
        registerSound("item.wolf_armor.damage");
        registerSound("item.wolf_armor.repair");
        registerSound("music.creative");
        registerSound("music.credits");
        registerSound("music_disc.5");
        registerSound("music_disc.creator");
        registerSound("music_disc.creator_music_box");
        registerSound("music_disc.otherside");
        registerSound("music_disc.pigstep");
        registerSound("music_disc.precipice");
        registerSound("music_disc.relic");
        registerSound("music.dragon");
        registerSound("music.end");
        registerSound("music.game");
        registerSound("music.menu");
        registerSound("music.nether.crimson_forest");
        registerSound("music.nether.nether_wastes");
        registerSound("music.nether.soul_sand_valley");
        registerSound("music.nether.warped_forest");
        registerSound("music.overworld.badlands");
        registerSound("music.overworld.bamboo_jungle");
        registerSound("music.overworld.cherry_grove");
        registerSound("music.overworld.deep_dark");
        registerSound("music.overworld.desert");
        registerSound("music.overworld.dripstone_caves");
        registerSound("music.overworld.flower_forest");
        registerSound("music.overworld.forest");
        registerSound("music.overworld.frozen_peaks");
        registerSound("music.overworld.grove");
        registerSound("music.overworld.jagged_peaks");
        registerSound("music.overworld.jungle");
        registerSound("music.overworld.lush_caves");
        registerSound("music.overworld.meadow");
        registerSound("music.overworld.old_growth_taiga");
        registerSound("music.overworld.snowy_slopes");
        registerSound("music.overworld.sparse_jungle");
        registerSound("music.overworld.stony_peaks");
        registerSound("music.overworld.swamp");
        registerSound("music.under_water");
        registerSound("particle.soul_escape");
        registerSound("ui.cartography_table.take_result");
        registerSound("ui.hud.bubble_pop");
        registerSound("ui.loom.select_pattern");
        registerSound("ui.loom.take_result");
        registerSound("ui.stonecutter.select_recipe");
        registerSound("ui.stonecutter.take_result");
        registerSound("ui.toast.challenge_complete");
        registerSound("ui.toast.in");
        registerSound("ui.toast.out");
        registerSound("weather.rain.above");
        registerSound("block.eyeblossom.close");
        registerSound("block.resin_bricks.fall");
        registerSound("block.resin_bricks.step");
        registerSound("block.resin.place");
        registerSound("entity.creaking.twitch");
        registerSound("block.eyeblossom.idle");
        registerSound("block.resin.break");
        registerSound("block.resin_bricks.place");
        registerSound("block.resin_bricks.break");
        registerSound("block.eyeblossom.close_long");
        registerSound("block.resin.fall");
        registerSound("block.resin.step");
        registerSound("block.eyeblossom.open");
        registerSound("block.resin_bricks.hit");
        registerSound("block.eyeblossom.open_long");
        registerSound("entity.wind_charge.wind_burst", "entity_generic_wind_burst");
        registerSound("music.overworld.jungle_and_forest");
        registerSound("block.trial_spawner.ambient_charged");
        registerSound("block.trial_spawner.charge_activate");
        registerSound("entity.goat.screaming.horn_break");
        registerSound("item.brush.brush_sand_completed");
        registerSound("item.goat_horn.play");
        registerSound("item.brush.brushing");
        registerSound("entity_parrot_imitate_wolf");
        registerSound("entity_parrot_imitate_polar_bear");
        registerSound("entity_parrot_imitate_panda");
        registerSound("entity_parrot_imitate_enderman");
        registerSound("block.cactus_flower.break");
        registerSound("block.cactus_flower.place");
        registerSound("block.deadbush.idle");
        registerSound("block.firefly_bush.idle");
        registerSound("block.iron.break");
        registerSound("block.iron.fall");
        registerSound("block.iron.hit");
        registerSound("block.iron.place");
        registerSound("block.iron.step");
        registerSound("block.leaf_litter.break");
        registerSound("block.leaf_litter.step");
        registerSound("block.leaf_litter.place");
        registerSound("block.leaf_litter.hit");
        registerSound("block.leaf_litter.fall");
        registerSound("block.sand.idle");
        registerSound("block.sand.wind");
        registerSound("entity.wolf_angry.ambient");
        registerSound("entity.wolf_angry.death");
        registerSound("entity.wolf_angry.growl");
        registerSound("entity.wolf_angry.hurt");
        registerSound("entity.wolf_angry.pant");
        registerSound("entity.wolf_angry.whine");
        registerSound("entity.wolf_big.ambient");
        registerSound("entity.wolf_big.death");
        registerSound("entity.wolf_big.growl");
        registerSound("entity.wolf_big.hurt");
        registerSound("entity.wolf_big.pant");
        registerSound("entity.wolf_big.whine");
        registerSound("entity.wolf_cute.ambient");
        registerSound("entity.wolf_cute.death");
        registerSound("entity.wolf_cute.growl");
        registerSound("entity.wolf_cute.hurt");
        registerSound("entity.wolf_cute.pant");
        registerSound("entity.wolf_cute.whine");
        registerSound("entity.wolf_grumpy.ambient");
        registerSound("entity.wolf_grumpy.death");
        registerSound("entity.wolf_grumpy.growl");
        registerSound("entity.wolf_grumpy.hurt");
        registerSound("entity.wolf_grumpy.pant");
        registerSound("entity.wolf_grumpy.whine");
        registerSound("entity.wolf_puglin.ambient");
        registerSound("entity.wolf_puglin.death");
        registerSound("entity.wolf_puglin.growl");
        registerSound("entity.wolf_puglin.hurt");
        registerSound("entity.wolf_puglin.pant");
        registerSound("entity.wolf_puglin.whine");
        registerSound("entity.wolf_sad.ambient");
        registerSound("entity.wolf_sad.death");
        registerSound("entity.wolf_sad.growl");
        registerSound("entity.wolf_sad.hurt");
        registerSound("entity.wolf_sad.pant");
        registerSound("entity.wolf_sad.whine");
        registerSound("block.dried_ghast.ambient");
        registerSound("block.dried_ghast.ambient_water");
        registerSound("block.dried_ghast.break");
        registerSound("block.dried_ghast.fall");
        registerSound("block.dried_ghast.place");
        registerSound("block.dried_ghast.place_in_water");
        registerSound("block.dried_ghast.step");
        registerSound("block.dried_ghast.transition");
        registerSound("block.dry_grass.ambient");
        registerSound("entity.ghastling.ambient");
        registerSound("entity.ghastling.death");
        registerSound("entity.ghastling.hurt");
        registerSound("entity.ghastling.spawn");
        registerSound("entity.happy_ghast.ambient");
        registerSound("entity.happy_ghast.death");
        registerSound("entity.happy_ghast.equip");
        registerSound("entity.happy_ghast.harness_goggles_down");
        registerSound("entity.happy_ghast.harness_goggles_up");
        registerSound("entity.happy_ghast.hurt");
        registerSound("entity.happy_ghast.riding");
        registerSound("entity.happy_ghast.unequip");
        registerSound("item.horse_armor.unequip");
        registerSound("item.lead.break");
        registerSound("item.lead.tied");
        registerSound("item.lead.untied");
        registerSound("item.llama_carpet.unequip");
        registerSound("item.saddle.unequip");
        registerSound("item.shears.snip");
        registerSound("music_disc.tears");
        registerSound("music_disc.lava_chicken");

        Map<String, Sound> underscoreAliases = new HashMap<>();
        for (Map.Entry<String, Sound> entry : SOUNDS.entrySet()) {
            String name = entry.getKey();
            if (name.contains(".")) {
                underscoreAliases.put(name.replace('.', '_'), entry.getValue());
            }
        }
        SOUNDS.putAll(underscoreAliases);
    }

}
